# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: core/api.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class HttpMethod(betterproto.Enum):
    GET = 0
    POST = 1
    PUT = 2
    DELETE = 3
    PATCH = 4
    OPTIONS = 5
    HEAD = 6
    CONNECT = 7
    TRACE = 8


@dataclass
class Endpoint(betterproto.Message):
    name: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    public: bool = betterproto.bool_field(3)
    api: "API" = betterproto.message_field(4)
    application: str = betterproto.string_field(5)
    service: str = betterproto.string_field(6)
    namespace: str = betterproto.string_field(7)


@dataclass
class ServiceEndpointGroup(betterproto.Message):
    name: str = betterproto.string_field(1)
    public: bool = betterproto.bool_field(2)
    endpoints: List["Endpoint"] = betterproto.message_field(3)


@dataclass
class ApplicationEndpointGroup(betterproto.Message):
    name: str = betterproto.string_field(1)
    public: bool = betterproto.bool_field(2)
    service_endpoint_groups: List["ServiceEndpointGroup"] = betterproto.message_field(3)


@dataclass
class EndpointGroup(betterproto.Message):
    application_endpoint_group: List[
        "ApplicationEndpointGroup"
    ] = betterproto.message_field(2)


@dataclass
class API(betterproto.Message):
    tcp: "TcpAPI" = betterproto.message_field(1, group="value")
    rest: "RestAPI" = betterproto.message_field(2, group="value")
    grpc: "GrpcAPI" = betterproto.message_field(3, group="value")


@dataclass
class RestRoute(betterproto.Message):
    methods: List["HttpMethod"] = betterproto.enum_field(1)
    path: str = betterproto.string_field(2)


@dataclass
class RestAPI(betterproto.Message):
    openapi: bytes = betterproto.bytes_field(1)
    routes: List["RestRoute"] = betterproto.message_field(2)


@dataclass
class GrpcAPI(betterproto.Message):
    proto: bytes = betterproto.bytes_field(1)


@dataclass
class HttpAPI(betterproto.Message):
    pass


@dataclass
class TcpAPI(betterproto.Message):
    pass
