# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: core/communicate.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


class Method(betterproto.Enum):
    UNKNOWN = 0
    # Factory
    CREATE = 1
    # Runtime
    SYNC = 10


@dataclass
class Channel(betterproto.Message):
    method: "Method" = betterproto.enum_field(1)


@dataclass
class Message(betterproto.Message):
    name: str = betterproto.string_field(1)
    message: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)


@dataclass
class Display(betterproto.Message):
    data: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class Confirm(betterproto.Message):
    default: bool = betterproto.bool_field(1)


@dataclass
class ConfirmAnswer(betterproto.Message):
    confirmed: bool = betterproto.bool_field(1)


@dataclass
class Input(betterproto.Message):
    string_default: str = betterproto.string_field(1, group="default")
    int_default: int = betterproto.int32_field(2, group="default")


@dataclass
class InputAnswer(betterproto.Message):
    string_value: str = betterproto.string_field(1, group="answer")
    int_value: int = betterproto.int32_field(2, group="answer")


@dataclass
class Choice(betterproto.Message):
    options: List["Message"] = betterproto.message_field(1)


@dataclass
class ChoiceAnswer(betterproto.Message):
    option: str = betterproto.string_field(1)


@dataclass
class Selection(betterproto.Message):
    options: List["Message"] = betterproto.message_field(1)


@dataclass
class SelectionAnswer(betterproto.Message):
    selected: List[str] = betterproto.string_field(1)


@dataclass
class Question(betterproto.Message):
    method: "Method" = betterproto.enum_field(1)
    round: int = betterproto.int32_field(2)
    message: "Message" = betterproto.message_field(3)
    display: "Display" = betterproto.message_field(4, group="value")
    confirm: "Confirm" = betterproto.message_field(5, group="value")
    input: "Input" = betterproto.message_field(6, group="value")
    choice: "Choice" = betterproto.message_field(7, group="value")
    selection: "Selection" = betterproto.message_field(8, group="value")


@dataclass
class Answer(betterproto.Message):
    done: bool = betterproto.bool_field(1)
    method: "Method" = betterproto.enum_field(2)
    round: int = betterproto.int32_field(3)
    error: str = betterproto.string_field(4)
    confirm: "ConfirmAnswer" = betterproto.message_field(5, group="value")
    input: "InputAnswer" = betterproto.message_field(6, group="value")
    choice: "ChoiceAnswer" = betterproto.message_field(7, group="value")
    selection: "SelectionAnswer" = betterproto.message_field(8, group="value")


@dataclass
class Engage(betterproto.Message):
    method: "Method" = betterproto.enum_field(1)
    answer: "Answer" = betterproto.message_field(2)


@dataclass
class InformationRequest(betterproto.Message):
    method: "Method" = betterproto.enum_field(1)
    done: bool = betterproto.bool_field(2)
    question: "Question" = betterproto.message_field(3)
