# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: services/factory/factory.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List, Optional

import betterproto
import grpclib

from .v1 import services
from .v1.core import api
from .v1.core import communicate


@dataclass
class InitResponse(betterproto.Message):
    version: services.Version = betterproto.message_field(1)
    channels: List[communicate.Channel] = betterproto.message_field(2)


@dataclass
class CreateRequest(betterproto.Message):
    pass


@dataclass
class CreateResponse(betterproto.Message):
    need_communication: bool = betterproto.bool_field(1)
    endpoints: List[api.Endpoint] = betterproto.message_field(2)


@dataclass
class UpdateRequest(betterproto.Message):
    pass


@dataclass
class UpdateResponse(betterproto.Message):
    pass


@dataclass
class SyncRequest(betterproto.Message):
    dependency_endpoint_group: api.EndpointGroup = betterproto.message_field(1)


@dataclass
class SyncResponse(betterproto.Message):
    need_communication: bool = betterproto.bool_field(1)


@dataclass
class BuildRequest(betterproto.Message):
    dependency_endpoint_group: api.EndpointGroup = betterproto.message_field(1)


@dataclass
class BuildResponse(betterproto.Message):
    pass


@dataclass
class DeploymentRequest(betterproto.Message):
    pass


@dataclass
class DeploymentResponse(betterproto.Message):
    pass


class FactoryStub(betterproto.ServiceStub):
    async def init(self) -> InitResponse:
        """Setup"""

        request = services.InitRequest()

        return await self._unary_unary(
            "/v1.services.factory.Factory/Init",
            request,
            InitResponse,
        )

    async def create(self) -> CreateResponse:
        """Affect Code"""

        request = CreateRequest()

        return await self._unary_unary(
            "/v1.services.factory.Factory/Create",
            request,
            CreateResponse,
        )

    async def update(self) -> UpdateResponse:
        request = UpdateRequest()

        return await self._unary_unary(
            "/v1.services.factory.Factory/Update",
            request,
            UpdateResponse,
        )

    async def sync(
        self, *, dependency_endpoint_group: Optional[api.EndpointGroup] = None
    ) -> SyncResponse:
        """Affect Data"""

        request = SyncRequest()
        if dependency_endpoint_group is not None:
            request.dependency_endpoint_group = dependency_endpoint_group

        return await self._unary_unary(
            "/v1.services.factory.Factory/Sync",
            request,
            SyncResponse,
        )

    async def build(
        self, *, dependency_endpoint_group: Optional[api.EndpointGroup] = None
    ) -> BuildResponse:
        """Deployment/Build only on init data"""

        request = BuildRequest()
        if dependency_endpoint_group is not None:
            request.dependency_endpoint_group = dependency_endpoint_group

        return await self._unary_unary(
            "/v1.services.factory.Factory/Build",
            request,
            BuildResponse,
        )

    async def deploy(self) -> DeploymentResponse:
        request = DeploymentRequest()

        return await self._unary_unary(
            "/v1.services.factory.Factory/Deploy",
            request,
            DeploymentResponse,
        )

    async def communicate(self) -> communicate.InformationRequest:
        """Communication helper"""

        request = communicate.Engage()

        return await self._unary_unary(
            "/v1.services.factory.Factory/Communicate",
            request,
            communicate.InformationRequest,
        )
