# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: services/runtime/tracker.proto, services/runtime/runtime.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List, Optional

import betterproto
import grpclib

from .v1 import services
from .v1.core import api
from .v1.core import communicate


class InitStatusState(betterproto.Enum):
    UNKNOWN = 0
    READY = 1
    ERROR = 2


class ConfigureStatusState(betterproto.Enum):
    UNKNOWN = 0
    READY = 1
    ERROR = 2


class StartStatusState(betterproto.Enum):
    UNKNOWN = 0
    STARTED = 1
    ERROR = 2


class InformationResponseStatus(betterproto.Enum):
    UNKNOWN = 0
    INIT = 1
    STARTED = 2
    RESTART_WANTED = 3
    SYNC_WANTED = 4
    STOPPED = 5
    ERROR = 6


@dataclass
class ProcessTracker(betterproto.Message):
    p_i_d: int = betterproto.int32_field(1)
    type: str = betterproto.string_field(2)


@dataclass
class DockerTracker(betterproto.Message):
    container_id: str = betterproto.string_field(1)


@dataclass
class Tracker(betterproto.Message):
    name: str = betterproto.string_field(1)
    process_tracker: "ProcessTracker" = betterproto.message_field(4, group="tracker")
    docker_tracker: "DockerTracker" = betterproto.message_field(5, group="tracker")


@dataclass
class TrackerList(betterproto.Message):
    trackers: List["Tracker"] = betterproto.message_field(1)


@dataclass
class Trackers(betterproto.Message):
    trackers: Dict[str, "TrackerList"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass
class InitStatus(betterproto.Message):
    state: "InitStatusState" = betterproto.enum_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class InitResponse(betterproto.Message):
    version: services.Version = betterproto.message_field(1)
    channels: List[communicate.Channel] = betterproto.message_field(2)
    endpoints: List[api.Endpoint] = betterproto.message_field(3)
    status: "InitStatus" = betterproto.message_field(4)


@dataclass
class ConfigureStatus(betterproto.Message):
    state: "ConfigureStatusState" = betterproto.enum_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class ConfigureRequest(betterproto.Message):
    pass


@dataclass
class ConfigureResponse(betterproto.Message):
    status: "ConfigureStatus" = betterproto.message_field(2)
    network_mappings: List["NetworkMapping"] = betterproto.message_field(3)


@dataclass
class NetworkMapping(betterproto.Message):
    application: str = betterproto.string_field(1)
    service: str = betterproto.string_field(2)
    endpoint: api.Endpoint = betterproto.message_field(3)
    addresses: List[str] = betterproto.string_field(4)


@dataclass
class StartRequest(betterproto.Message):
    network_mappings: List["NetworkMapping"] = betterproto.message_field(1)
    dependency_endpoint_group: api.EndpointGroup = betterproto.message_field(2)


@dataclass
class StartStatus(betterproto.Message):
    state: "StartStatusState" = betterproto.enum_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class StartResponse(betterproto.Message):
    status: "StartStatus" = betterproto.message_field(1)
    trackers: List["Tracker"] = betterproto.message_field(2)


@dataclass
class InformationRequest(betterproto.Message):
    pass


@dataclass
class InformationResponse(betterproto.Message):
    status: "InformationResponseStatus" = betterproto.enum_field(1)


@dataclass
class StopRequest(betterproto.Message):
    persist: bool = betterproto.bool_field(1)


@dataclass
class StopResponse(betterproto.Message):
    pass


class RuntimeStub(betterproto.ServiceStub):
    async def init(self) -> InitResponse:
        request = services.InitRequest()

        return await self._unary_unary(
            "/v1.services.runtime.Runtime/Init",
            request,
            InitResponse,
        )

    async def configure(self) -> ConfigureResponse:
        request = ConfigureRequest()

        return await self._unary_unary(
            "/v1.services.runtime.Runtime/Configure",
            request,
            ConfigureResponse,
        )

    async def start(
        self,
        *,
        network_mappings: List["NetworkMapping"] = [],
        dependency_endpoint_group: Optional[api.EndpointGroup] = None,
    ) -> StartResponse:
        request = StartRequest()
        if network_mappings is not None:
            request.network_mappings = network_mappings
        if dependency_endpoint_group is not None:
            request.dependency_endpoint_group = dependency_endpoint_group

        return await self._unary_unary(
            "/v1.services.runtime.Runtime/Start",
            request,
            StartResponse,
        )

    async def information(self) -> InformationResponse:
        request = InformationRequest()

        return await self._unary_unary(
            "/v1.services.runtime.Runtime/Information",
            request,
            InformationResponse,
        )

    async def stop(self, *, persist: bool = False) -> StopResponse:
        request = StopRequest()
        request.persist = persist

        return await self._unary_unary(
            "/v1.services.runtime.Runtime/Stop",
            request,
            StopResponse,
        )

    async def communicate(self) -> communicate.InformationRequest:
        """Communication helper"""

        request = communicate.Engage()

        return await self._unary_unary(
            "/v1.services.runtime.Runtime/Communicate",
            request,
            communicate.InformationRequest,
        )
