# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: actions/project.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class AddProject(betterproto.Message):
    kind: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)


@dataclass
class AddProjectOutput(betterproto.Message):
    name: str = betterproto.string_field(1)
