# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: providers/provider.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class InitRequest(betterproto.Message):
    pass


@dataclass
class InitResponse(betterproto.Message):
    pass


class ProviderStub(betterproto.ServiceStub):
    async def init(self) -> InitResponse:
        request = InitRequest()

        return await self._unary_unary(
            "/v1.provider.Provider/Init",
            request,
            InitResponse,
        )
