# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: services/init.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .v1.core import api


@dataclass
class Version(betterproto.Message):
    version: str = betterproto.string_field(1)


@dataclass
class ServiceIdentity(betterproto.Message):
    name: str = betterproto.string_field(1)
    domain: str = betterproto.string_field(2)
    application: str = betterproto.string_field(3)
    namespace: str = betterproto.string_field(4)


@dataclass
class InitRequest(betterproto.Message):
    debug: bool = betterproto.bool_field(1)
    # Location of the service on the filesystem
    location: str = betterproto.string_field(2)
    # Identity of the service
    identity: "ServiceIdentity" = betterproto.message_field(3)
    # Dependency EndpointGroup
    dependency_endpoint_group: api.EndpointGroup = betterproto.message_field(4)
