// Code generated by go-swagger; DO NOT EDIT.

package organization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new organization service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for organization service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	OrganizationServiceCreateOrganization(params *OrganizationServiceCreateOrganizationParams, opts ...ClientOption) (*OrganizationServiceCreateOrganizationOK, error)

	OrganizationServiceCreateSelf(params *OrganizationServiceCreateSelfParams, opts ...ClientOption) (*OrganizationServiceCreateSelfOK, error)

	OrganizationServiceGetSelf(params *OrganizationServiceGetSelfParams, opts ...ClientOption) (*OrganizationServiceGetSelfOK, error)

	OrganizationServiceVersion(params *OrganizationServiceVersionParams, opts ...ClientOption) (*OrganizationServiceVersionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
OrganizationServiceCreateOrganization organization service create organization API
*/
func (a *Client) OrganizationServiceCreateOrganization(params *OrganizationServiceCreateOrganizationParams, opts ...ClientOption) (*OrganizationServiceCreateOrganizationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrganizationServiceCreateOrganizationParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "OrganizationService_CreateOrganization",
		Method:             "POST",
		PathPattern:        "/management/organization/organization",
		ProducesMediaTypes: []string{"module/json"},
		ConsumesMediaTypes: []string{"module/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrganizationServiceCreateOrganizationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OrganizationServiceCreateOrganizationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OrganizationServiceCreateOrganizationDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
OrganizationServiceCreateSelf organization service create self API
*/
func (a *Client) OrganizationServiceCreateSelf(params *OrganizationServiceCreateSelfParams, opts ...ClientOption) (*OrganizationServiceCreateSelfOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrganizationServiceCreateSelfParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "OrganizationService_CreateSelf",
		Method:             "POST",
		PathPattern:        "/management/organization/user",
		ProducesMediaTypes: []string{"module/json"},
		ConsumesMediaTypes: []string{"module/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrganizationServiceCreateSelfReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OrganizationServiceCreateSelfOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OrganizationServiceCreateSelfDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
OrganizationServiceGetSelf organization service get self API
*/
func (a *Client) OrganizationServiceGetSelf(params *OrganizationServiceGetSelfParams, opts ...ClientOption) (*OrganizationServiceGetSelfOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrganizationServiceGetSelfParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "OrganizationService_GetSelf",
		Method:             "GET",
		PathPattern:        "/management/organization/user",
		ProducesMediaTypes: []string{"module/json"},
		ConsumesMediaTypes: []string{"module/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrganizationServiceGetSelfReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OrganizationServiceGetSelfOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OrganizationServiceGetSelfDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
OrganizationServiceVersion organization service version API
*/
func (a *Client) OrganizationServiceVersion(params *OrganizationServiceVersionParams, opts ...ClientOption) (*OrganizationServiceVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOrganizationServiceVersionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "OrganizationService_Version",
		Method:             "GET",
		PathPattern:        "/management/organization/version",
		ProducesMediaTypes: []string{"module/json"},
		ConsumesMediaTypes: []string{"module/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &OrganizationServiceVersionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OrganizationServiceVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*OrganizationServiceVersionDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
