// Code generated by go-swagger; DO NOT EDIT.

package organization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/codefly-dev/cli/pkg/platform/models"
)

// OrganizationServiceCreateOrganizationReader is a Reader for the OrganizationServiceCreateOrganization structure.
type OrganizationServiceCreateOrganizationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationServiceCreateOrganizationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationServiceCreateOrganizationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewOrganizationServiceCreateOrganizationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOrganizationServiceCreateOrganizationOK creates a OrganizationServiceCreateOrganizationOK with default headers values
func NewOrganizationServiceCreateOrganizationOK() *OrganizationServiceCreateOrganizationOK {
	return &OrganizationServiceCreateOrganizationOK{}
}

/*
OrganizationServiceCreateOrganizationOK describes a response with status code 200, with default header values.

A successful response.
*/
type OrganizationServiceCreateOrganizationOK struct {
	Payload *models.OrganizationCreateOrganizationResponse
}

// IsSuccess returns true when this organization service create organization o k response has a 2xx status code
func (o *OrganizationServiceCreateOrganizationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organization service create organization o k response has a 3xx status code
func (o *OrganizationServiceCreateOrganizationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization service create organization o k response has a 4xx status code
func (o *OrganizationServiceCreateOrganizationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organization service create organization o k response has a 5xx status code
func (o *OrganizationServiceCreateOrganizationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organization service create organization o k response a status code equal to that given
func (o *OrganizationServiceCreateOrganizationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the organization service create organization o k response
func (o *OrganizationServiceCreateOrganizationOK) Code() int {
	return 200
}

func (o *OrganizationServiceCreateOrganizationOK) Error() string {
	return fmt.Sprintf("[POST /management/organization/organization][%d] organizationServiceCreateOrganizationOK  %+v", 200, o.Payload)
}

func (o *OrganizationServiceCreateOrganizationOK) String() string {
	return fmt.Sprintf("[POST /management/organization/organization][%d] organizationServiceCreateOrganizationOK  %+v", 200, o.Payload)
}

func (o *OrganizationServiceCreateOrganizationOK) GetPayload() *models.OrganizationCreateOrganizationResponse {
	return o.Payload
}

func (o *OrganizationServiceCreateOrganizationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrganizationCreateOrganizationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrganizationServiceCreateOrganizationDefault creates a OrganizationServiceCreateOrganizationDefault with default headers values
func NewOrganizationServiceCreateOrganizationDefault(code int) *OrganizationServiceCreateOrganizationDefault {
	return &OrganizationServiceCreateOrganizationDefault{
		_statusCode: code,
	}
}

/*
OrganizationServiceCreateOrganizationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type OrganizationServiceCreateOrganizationDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this organization service create organization default response has a 2xx status code
func (o *OrganizationServiceCreateOrganizationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this organization service create organization default response has a 3xx status code
func (o *OrganizationServiceCreateOrganizationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this organization service create organization default response has a 4xx status code
func (o *OrganizationServiceCreateOrganizationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this organization service create organization default response has a 5xx status code
func (o *OrganizationServiceCreateOrganizationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this organization service create organization default response a status code equal to that given
func (o *OrganizationServiceCreateOrganizationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the organization service create organization default response
func (o *OrganizationServiceCreateOrganizationDefault) Code() int {
	return o._statusCode
}

func (o *OrganizationServiceCreateOrganizationDefault) Error() string {
	return fmt.Sprintf("[POST /management/organization/organization][%d] OrganizationService_CreateOrganization default  %+v", o._statusCode, o.Payload)
}

func (o *OrganizationServiceCreateOrganizationDefault) String() string {
	return fmt.Sprintf("[POST /management/organization/organization][%d] OrganizationService_CreateOrganization default  %+v", o._statusCode, o.Payload)
}

func (o *OrganizationServiceCreateOrganizationDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *OrganizationServiceCreateOrganizationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
