// Code generated by go-swagger; DO NOT EDIT.

package organization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrganizationServiceVersionParams creates a new OrganizationServiceVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrganizationServiceVersionParams() *OrganizationServiceVersionParams {
	return &OrganizationServiceVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrganizationServiceVersionParamsWithTimeout creates a new OrganizationServiceVersionParams object
// with the ability to set a timeout on a request.
func NewOrganizationServiceVersionParamsWithTimeout(timeout time.Duration) *OrganizationServiceVersionParams {
	return &OrganizationServiceVersionParams{
		timeout: timeout,
	}
}

// NewOrganizationServiceVersionParamsWithContext creates a new OrganizationServiceVersionParams object
// with the ability to set a context for a request.
func NewOrganizationServiceVersionParamsWithContext(ctx context.Context) *OrganizationServiceVersionParams {
	return &OrganizationServiceVersionParams{
		Context: ctx,
	}
}

// NewOrganizationServiceVersionParamsWithHTTPClient creates a new OrganizationServiceVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrganizationServiceVersionParamsWithHTTPClient(client *http.Client) *OrganizationServiceVersionParams {
	return &OrganizationServiceVersionParams{
		HTTPClient: client,
	}
}

/*
OrganizationServiceVersionParams contains all the parameters to send to the API endpoint

	for the organization service version operation.

	Typically these are written to a http.Request.
*/
type OrganizationServiceVersionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the organization service version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationServiceVersionParams) WithDefaults() *OrganizationServiceVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the organization service version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationServiceVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the organization service version params
func (o *OrganizationServiceVersionParams) WithTimeout(timeout time.Duration) *OrganizationServiceVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the organization service version params
func (o *OrganizationServiceVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the organization service version params
func (o *OrganizationServiceVersionParams) WithContext(ctx context.Context) *OrganizationServiceVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the organization service version params
func (o *OrganizationServiceVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the organization service version params
func (o *OrganizationServiceVersionParams) WithHTTPClient(client *http.Client) *OrganizationServiceVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the organization service version params
func (o *OrganizationServiceVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OrganizationServiceVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
