// Code generated by go-swagger; DO NOT EDIT.

package organization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/codefly-dev/cli/pkg/platform/models"
)

// OrganizationServiceGetSelfReader is a Reader for the OrganizationServiceGetSelf structure.
type OrganizationServiceGetSelfReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationServiceGetSelfReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationServiceGetSelfOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewOrganizationServiceGetSelfDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOrganizationServiceGetSelfOK creates a OrganizationServiceGetSelfOK with default headers values
func NewOrganizationServiceGetSelfOK() *OrganizationServiceGetSelfOK {
	return &OrganizationServiceGetSelfOK{}
}

/*
OrganizationServiceGetSelfOK describes a response with status code 200, with default header values.

A successful response.
*/
type OrganizationServiceGetSelfOK struct {
	Payload *models.OrganizationGetUserResponse
}

// IsSuccess returns true when this organization service get self o k response has a 2xx status code
func (o *OrganizationServiceGetSelfOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organization service get self o k response has a 3xx status code
func (o *OrganizationServiceGetSelfOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization service get self o k response has a 4xx status code
func (o *OrganizationServiceGetSelfOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organization service get self o k response has a 5xx status code
func (o *OrganizationServiceGetSelfOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organization service get self o k response a status code equal to that given
func (o *OrganizationServiceGetSelfOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the organization service get self o k response
func (o *OrganizationServiceGetSelfOK) Code() int {
	return 200
}

func (o *OrganizationServiceGetSelfOK) Error() string {
	return fmt.Sprintf("[GET /management/organization/user][%d] organizationServiceGetSelfOK  %+v", 200, o.Payload)
}

func (o *OrganizationServiceGetSelfOK) String() string {
	return fmt.Sprintf("[GET /management/organization/user][%d] organizationServiceGetSelfOK  %+v", 200, o.Payload)
}

func (o *OrganizationServiceGetSelfOK) GetPayload() *models.OrganizationGetUserResponse {
	return o.Payload
}

func (o *OrganizationServiceGetSelfOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrganizationGetUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrganizationServiceGetSelfDefault creates a OrganizationServiceGetSelfDefault with default headers values
func NewOrganizationServiceGetSelfDefault(code int) *OrganizationServiceGetSelfDefault {
	return &OrganizationServiceGetSelfDefault{
		_statusCode: code,
	}
}

/*
OrganizationServiceGetSelfDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type OrganizationServiceGetSelfDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this organization service get self default response has a 2xx status code
func (o *OrganizationServiceGetSelfDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this organization service get self default response has a 3xx status code
func (o *OrganizationServiceGetSelfDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this organization service get self default response has a 4xx status code
func (o *OrganizationServiceGetSelfDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this organization service get self default response has a 5xx status code
func (o *OrganizationServiceGetSelfDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this organization service get self default response a status code equal to that given
func (o *OrganizationServiceGetSelfDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the organization service get self default response
func (o *OrganizationServiceGetSelfDefault) Code() int {
	return o._statusCode
}

func (o *OrganizationServiceGetSelfDefault) Error() string {
	return fmt.Sprintf("[GET /management/organization/user][%d] OrganizationService_GetSelf default  %+v", o._statusCode, o.Payload)
}

func (o *OrganizationServiceGetSelfDefault) String() string {
	return fmt.Sprintf("[GET /management/organization/user][%d] OrganizationService_GetSelf default  %+v", o._statusCode, o.Payload)
}

func (o *OrganizationServiceGetSelfDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *OrganizationServiceGetSelfDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
