// Code generated by go-swagger; DO NOT EDIT.

package organization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/codefly-dev/cli/pkg/platform/models"
)

// OrganizationServiceVersionReader is a Reader for the OrganizationServiceVersion structure.
type OrganizationServiceVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrganizationServiceVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrganizationServiceVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewOrganizationServiceVersionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOrganizationServiceVersionOK creates a OrganizationServiceVersionOK with default headers values
func NewOrganizationServiceVersionOK() *OrganizationServiceVersionOK {
	return &OrganizationServiceVersionOK{}
}

/*
OrganizationServiceVersionOK describes a response with status code 200, with default header values.

A successful response.
*/
type OrganizationServiceVersionOK struct {
	Payload *models.OrganizationVersionResponse
}

// IsSuccess returns true when this organization service version o k response has a 2xx status code
func (o *OrganizationServiceVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this organization service version o k response has a 3xx status code
func (o *OrganizationServiceVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this organization service version o k response has a 4xx status code
func (o *OrganizationServiceVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this organization service version o k response has a 5xx status code
func (o *OrganizationServiceVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this organization service version o k response a status code equal to that given
func (o *OrganizationServiceVersionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the organization service version o k response
func (o *OrganizationServiceVersionOK) Code() int {
	return 200
}

func (o *OrganizationServiceVersionOK) Error() string {
	return fmt.Sprintf("[GET /management/organization/version][%d] organizationServiceVersionOK  %+v", 200, o.Payload)
}

func (o *OrganizationServiceVersionOK) String() string {
	return fmt.Sprintf("[GET /management/organization/version][%d] organizationServiceVersionOK  %+v", 200, o.Payload)
}

func (o *OrganizationServiceVersionOK) GetPayload() *models.OrganizationVersionResponse {
	return o.Payload
}

func (o *OrganizationServiceVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrganizationVersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOrganizationServiceVersionDefault creates a OrganizationServiceVersionDefault with default headers values
func NewOrganizationServiceVersionDefault(code int) *OrganizationServiceVersionDefault {
	return &OrganizationServiceVersionDefault{
		_statusCode: code,
	}
}

/*
OrganizationServiceVersionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type OrganizationServiceVersionDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this organization service version default response has a 2xx status code
func (o *OrganizationServiceVersionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this organization service version default response has a 3xx status code
func (o *OrganizationServiceVersionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this organization service version default response has a 4xx status code
func (o *OrganizationServiceVersionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this organization service version default response has a 5xx status code
func (o *OrganizationServiceVersionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this organization service version default response a status code equal to that given
func (o *OrganizationServiceVersionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the organization service version default response
func (o *OrganizationServiceVersionDefault) Code() int {
	return o._statusCode
}

func (o *OrganizationServiceVersionDefault) Error() string {
	return fmt.Sprintf("[GET /management/organization/version][%d] OrganizationService_Version default  %+v", o._statusCode, o.Payload)
}

func (o *OrganizationServiceVersionDefault) String() string {
	return fmt.Sprintf("[GET /management/organization/version][%d] OrganizationService_Version default  %+v", o._statusCode, o.Payload)
}

func (o *OrganizationServiceVersionDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *OrganizationServiceVersionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
