// Code generated by go-swagger; DO NOT EDIT.

package organization_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrganizationServiceCreateSelfParams creates a new OrganizationServiceCreateSelfParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrganizationServiceCreateSelfParams() *OrganizationServiceCreateSelfParams {
	return &OrganizationServiceCreateSelfParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrganizationServiceCreateSelfParamsWithTimeout creates a new OrganizationServiceCreateSelfParams object
// with the ability to set a timeout on a request.
func NewOrganizationServiceCreateSelfParamsWithTimeout(timeout time.Duration) *OrganizationServiceCreateSelfParams {
	return &OrganizationServiceCreateSelfParams{
		timeout: timeout,
	}
}

// NewOrganizationServiceCreateSelfParamsWithContext creates a new OrganizationServiceCreateSelfParams object
// with the ability to set a context for a request.
func NewOrganizationServiceCreateSelfParamsWithContext(ctx context.Context) *OrganizationServiceCreateSelfParams {
	return &OrganizationServiceCreateSelfParams{
		Context: ctx,
	}
}

// NewOrganizationServiceCreateSelfParamsWithHTTPClient creates a new OrganizationServiceCreateSelfParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrganizationServiceCreateSelfParamsWithHTTPClient(client *http.Client) *OrganizationServiceCreateSelfParams {
	return &OrganizationServiceCreateSelfParams{
		HTTPClient: client,
	}
}

/*
OrganizationServiceCreateSelfParams contains all the parameters to send to the API endpoint

	for the organization service create self operation.

	Typically these are written to a http.Request.
*/
type OrganizationServiceCreateSelfParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the organization service create self params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationServiceCreateSelfParams) WithDefaults() *OrganizationServiceCreateSelfParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the organization service create self params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationServiceCreateSelfParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the organization service create self params
func (o *OrganizationServiceCreateSelfParams) WithTimeout(timeout time.Duration) *OrganizationServiceCreateSelfParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the organization service create self params
func (o *OrganizationServiceCreateSelfParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the organization service create self params
func (o *OrganizationServiceCreateSelfParams) WithContext(ctx context.Context) *OrganizationServiceCreateSelfParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the organization service create self params
func (o *OrganizationServiceCreateSelfParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the organization service create self params
func (o *OrganizationServiceCreateSelfParams) WithHTTPClient(client *http.Client) *OrganizationServiceCreateSelfParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the organization service create self params
func (o *OrganizationServiceCreateSelfParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OrganizationServiceCreateSelfParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
