package gitops

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/codefly-dev/cli/pkg/environments"
	"github.com/codefly-dev/core/resources"
	"github.com/stretchr/testify/require"
)

func TestActualSharedIdentityCoordinateReachesRenderedAccounts(t *testing.T) {
	// Generated by infra-base's coordinate-contract verb, not a private adapter.
	data, err := os.ReadFile(filepath.Join("..", "environments", "testdata", "coordinates", "infra-base-platform-obin.json"))
	require.NoError(t, err)
	contract, err := environments.ParseCoordinateContract(data)
	require.NoError(t, err)
	env := &contract.Environment
	// This is the resolved, in-memory composition; the authored product retains
	// its versioned workspace and solution references.
	workspace := &resources.Workspace{Name: "platform-obin", Layout: resources.LayoutKindModules,
		Modules: []*resources.ModuleReference{{Name: "saas"}, {Name: "wiki"}}}
	scope := moduleScope(env, workspace, "saas")
	require.Equal(t, "platform-obin-saas", scope.Namespace)
	root := t.TempDir()
	writeConsumerTree(t, root, env.Name, scope.Namespace, "accounts", "declared.example")
	require.NoError(t, projectServiceConfiguration(t.Context(), root, &resources.Service{Name: "accounts"}, env, scope))
	seen := false
	for _, doc := range buildOverlay(t, root, env.Name) {
		if doc.kind != "ExternalSecret" {
			continue
		}
		seen = true
		spec := doc.value["spec"].(map[string]any)
		require.Equal(t, "cell-secrets", spec["secretStoreRef"].(map[string]any)["name"])
		entries := spec["data"].([]any)
		require.Len(t, entries, 2)
		for _, item := range entries {
			entry := item.(map[string]any)
			require.Equal(t, "workos-product-ripe-elephant-45-staging-authkit-app", entry["remoteRef"].(map[string]any)["key"])
			require.Equal(t, map[string]any{"storeRef": map[string]any{"name": "platform-obin-identity", "kind": "ClusterSecretStore"}}, entry["sourceRef"])
		}
	}
	require.True(t, seen)
}

func TestSecretProjectionKeepsSharedAndLocalStoresSeparate(t *testing.T) {
	env := injectionContract(t)
	mapping := env.ServiceSecrets.Services["api"]
	ref := mapping.RemoteKeys["DATABASE_PASSWORD"]
	ref.SecretStore = &environments.EnvironmentSecretStoreReference{Name: "shared-identity", Kind: "ClusterSecretStore"}
	mapping.RemoteKeys["DATABASE_PASSWORD"] = ref
	mapping.RemoteKeys["LOCAL_TOKEN"] = environments.EnvironmentSecretRemoteRef{Key: "local-token"}
	env.ServiceSecrets.Services["api"] = mapping
	root := t.TempDir()
	writeConsumerTree(t, root, env.Name, env.Namespace, "api", "declared.example")
	service := &resources.Service{Name: "api"}
	require.NoError(t, projectServiceConfiguration(t.Context(), root, service, env, scopeOf(env)))
	seen := map[string]bool{}
	for _, doc := range buildOverlay(t, root, env.Name) {
		if doc.kind != "ExternalSecret" {
			continue
		}
		spec := doc.value["spec"].(map[string]any)
		require.Equal(t, env.ServiceSecrets.SecretStore.Name, spec["secretStoreRef"].(map[string]any)["name"])
		for _, item := range spec["data"].([]any) {
			entry := item.(map[string]any)
			key := entry["secretKey"].(string)
			seen[key] = true
			if key == "DATABASE_PASSWORD" {
				require.Equal(t, map[string]any{"storeRef": map[string]any{"name": "shared-identity", "kind": "ClusterSecretStore"}}, entry["sourceRef"])
			} else {
				require.NotContains(t, entry, "sourceRef")
			}
		}
	}
	require.True(t, seen["DATABASE_PASSWORD"])
	require.True(t, seen["LOCAL_TOKEN"])
	addProjectionPatch(t, root, env.Name, "ExternalSecret", "- op: replace\n  path: /spec/data/0/sourceRef/storeRef/name\n  value: other-tenant")
	require.ErrorContains(t, projectServiceConfiguration(t.Context(), root, service, env, scopeOf(env)), "ExternalSecret")
}

func TestSecretProjectionRefusesInvalidPerKeyStore(t *testing.T) {
	secrets := cellServiceSecrets(environments.EnvironmentServiceSecretMapping{
		RemoteKeys: map[string]environments.EnvironmentSecretRemoteRef{
			"TOKEN": {Key: "shared-token", SecretStore: &environments.EnvironmentSecretStoreReference{Name: "shared", Kind: "Invalid"}},
		},
	})
	_, err := serviceSecretProjection(unitScope{Namespace: "product"}, "accounts", secrets, []string{"TOKEN"})
	require.ErrorContains(t, err, "source store")
}
