// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrganizationUser organization user
//
// swagger:model organizationUser
type OrganizationUser struct {

	// email
	Email string `json:"email,omitempty"`

	// given name
	GivenName string `json:"givenName,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// signup auth Id
	SignupAuthID string `json:"signupAuthId,omitempty"`
}

// Validate validates this organization user
func (m *OrganizationUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this organization user based on context it is used
func (m *OrganizationUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationUser) UnmarshalBinary(b []byte) error {
	var res OrganizationUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
