// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrganizationVersionResponse organization version response
//
// swagger:model organizationVersionResponse
type OrganizationVersionResponse struct {

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this organization version response
func (m *OrganizationVersionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this organization version response based on context it is used
func (m *OrganizationVersionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationVersionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationVersionResponse) UnmarshalBinary(b []byte) error {
	var res OrganizationVersionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
