// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrganizationOrganization organization organization
//
// swagger:model organizationOrganization
type OrganizationOrganization struct {

	// Domain corresponds vaguely to the organization URL in Github
	Domain string `json:"domain,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this organization organization
func (m *OrganizationOrganization) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this organization organization based on context it is used
func (m *OrganizationOrganization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationOrganization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationOrganization) UnmarshalBinary(b []byte) error {
	var res OrganizationOrganization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
