// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrganizationCreateOrganizationRequest organization create organization request
//
// swagger:model organizationCreateOrganizationRequest
type OrganizationCreateOrganizationRequest struct {

	// domain
	Domain string `json:"domain,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this organization create organization request
func (m *OrganizationCreateOrganizationRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this organization create organization request based on context it is used
func (m *OrganizationCreateOrganizationRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrganizationCreateOrganizationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrganizationCreateOrganizationRequest) UnmarshalBinary(b []byte) error {
	var res OrganizationCreateOrganizationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
