package generate

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"time"

	"github.com/codefly-dev/cli/cmd/common"
	"github.com/codefly-dev/cli/pkg/cli"
	"github.com/codefly-dev/cli/pkg/generators"
	"github.com/codefly-dev/core/companions/proto"
	"github.com/codefly-dev/core/composition"
	basev0 "github.com/codefly-dev/core/generated/go/codefly/base/v0"
	resources "github.com/codefly-dev/core/resources"
	runners "github.com/codefly-dev/core/runners/dockerrun"
	"github.com/codefly-dev/core/shared"
	"github.com/codefly-dev/core/standards"
	"github.com/spf13/cobra"
	googleproto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"gopkg.in/yaml.v3"
)

var (
	contractsOutput string
	contractsCheck  bool
	contractsFormat string
)

// yamlStringTag is the yaml.v3 tag for a plain string scalar node.
const yamlStringTag = "!!str"

// ContractsCmd exports every endpoint a module's interface declares into
// contracts/api and writes the catalog the module package carries.
var ContractsCmd = &cobra.Command{
	Use:   "contracts [module]",
	Short: "Export a module's interface endpoints as API contracts into its package",
	Long: `Export the API contract of every endpoint a module's interface exposes into
contracts/api and write the catalog (contracts/api/catalog.codefly.json), so the
module package carries the contract.

gRPC and connect endpoints get a serialized FileDescriptorSet (contract.binpb)
plus a copy of the service's proto sources; REST endpoints get their OpenAPI
document (openapi.json). HTTP and TCP endpoints have no machine-readable
contract and are skipped.

Run it before module-package build; the package carries the result. --check
is the CI drift gate: it regenerates into a temporary directory and compares
against what's on disk, without writing anything.
`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, done := common.NewContext()
		defer done()
		ctx, stop := common.SignalContext(ctx)
		defer stop()

		if contractsFormat != "text" && contractsFormat != "json" {
			return fmt.Errorf("--format must be text or json, got %q", contractsFormat)
		}

		workspace, err := common.LoadWorkspace(ctx)
		if err != nil {
			return err
		}

		var module *resources.Module
		if len(args) == 1 {
			module, err = workspace.LoadModuleFromName(ctx, args[0])
		} else {
			module, err = common.LoadModule(ctx)
		}
		if err != nil {
			return err
		}

		output := contractsOutput
		if output == "" {
			output = filepath.Join(module.Dir(), "contracts", "api")
		} else if output, err = shared.SolvePath(output); err != nil {
			return fmt.Errorf("cannot solve output path: %w", err)
		}

		if contractsCheck {
			return runContractsCheck(ctx, workspace, module, output)
		}

		catalog, err := generateContracts(ctx, workspace, module, generateOptions{
			canonicalOutput: output,
			writeDir:        output,
			updateManifest:  true,
		})
		if err != nil {
			return err
		}

		if contractsFormat == "json" {
			data, err := catalog.CanonicalBytes()
			if err != nil {
				return err
			}
			fmt.Println(string(data))
		}
		cli.Header(1, "Contracts generated successfully!")
		return nil
	},
}

func init() {
	ContractsCmd.Flags().StringVar(&contractsOutput, "output", "", "output directory for generated contracts (default: <module dir>/contracts/api)")
	ContractsCmd.Flags().BoolVar(&contractsCheck, "check", false, "do not write; exit 1 if the on-disk catalog differs from what would be generated")
	ContractsCmd.Flags().StringVar(&contractsFormat, "format", "text", "output format: text|json")
}

// generateOptions separates where generated bytes are canonically reported to
// live (canonicalOutput, used to compute each contract's module-relative Path)
// from where they are physically written (writeDir). --check stages bytes in a
// throwaway directory while still recording the Path a real run would produce,
// so the resulting catalog is diffable against the real output.
type generateOptions struct {
	canonicalOutput string
	writeDir        string
	updateManifest  bool
}

// generateContracts implements the command's core behaviour: load the
// module's exported endpoints, load each owning service's Builder only when
// at least one of its exported endpoints needs one, write the contract files,
// and assemble + write the catalog (and, when requested, the package
// manifest's api-contracts).
func generateContracts(ctx context.Context, workspace *resources.Workspace, module *resources.Module, opts generateOptions) (*composition.APIContractCatalog, error) {
	endpoints, err := module.ExportedEndpointsForPackage(ctx)
	if err != nil {
		return nil, fmt.Errorf("%w; add an interface: block to module.codefly.yaml to export API contracts", err)
	}

	var serviceNames []string
	byService := map[string][]*basev0.Endpoint{}
	for _, endpoint := range endpoints {
		if _, seen := byService[endpoint.Service]; !seen {
			serviceNames = append(serviceNames, endpoint.Service)
		}
		byService[endpoint.Service] = append(byService[endpoint.Service], endpoint)
	}
	sort.Strings(serviceNames)

	if _, err = shared.CheckDirectoryOrCreate(ctx, opts.writeDir); err != nil {
		return nil, fmt.Errorf("cannot create output directory: %w", err)
	}

	var contractEndpoints []composition.APIContractEndpoint
	for _, serviceName := range serviceNames {
		exported := byService[serviceName]

		needsBuilder := false
		for _, endpoint := range exported {
			if endpoint.Api == standards.GRPC || endpoint.Api == standards.REST {
				needsBuilder = true
				break
			}
		}
		if !needsBuilder {
			for _, endpoint := range exported {
				cli.Info("endpoint %s/%s (api %s) has no contract; skipped", serviceName, endpoint.Name, endpoint.Api)
			}
			continue
		}

		service, loadErr := module.LoadServiceFromName(ctx, serviceName)
		if loadErr != nil {
			return nil, fmt.Errorf("cannot load service %s: %w", serviceName, loadErr)
		}
		loaded, loadErr := generators.LoadServiceEndpoints(ctx, workspace, module, service)
		if loadErr != nil {
			return nil, fmt.Errorf("cannot load endpoints for service %s: %w", serviceName, loadErr)
		}
		loadedByName := make(map[string]*basev0.Endpoint, len(loaded))
		for _, endpoint := range loaded {
			loadedByName[endpoint.Name] = endpoint
		}

		for _, endpoint := range exported {
			if endpoint.Api != standards.GRPC && endpoint.Api != standards.REST {
				cli.Info("endpoint %s/%s (api %s) has no contract; skipped", serviceName, endpoint.Name, endpoint.Api)
				continue
			}
			actual, ok := loadedByName[endpoint.Name]
			if !ok {
				return nil, fmt.Errorf("service %s does not report endpoint %q at Builder.Load", serviceName, endpoint.Name)
			}
			contractEndpoint, writeErr := writeEndpointContract(ctx, module, service, actual, opts)
			if writeErr != nil {
				return nil, fmt.Errorf("cannot write contract for %s/%s: %w", serviceName, endpoint.Name, writeErr)
			}
			contractEndpoints = append(contractEndpoints, *contractEndpoint)
			printContractLine(contractEndpoint)
		}
	}

	pkg, version, manifest, err := resolvePackageIdentity(module)
	if err != nil {
		return nil, err
	}

	catalog := &composition.APIContractCatalog{
		Schema:    composition.APIContractCatalogSchema,
		Package:   pkg,
		Version:   version,
		Endpoints: contractEndpoints,
	}
	if err = catalog.Validate(); err != nil {
		return nil, fmt.Errorf("generated catalog is invalid: %w", err)
	}

	catalogBytes, err := catalog.CanonicalBytes()
	if err != nil {
		return nil, err
	}
	if err := shared.WriteFileAtomic(ctx, filepath.Join(opts.writeDir, "catalog.codefly.json"), catalogBytes, 0o644); err != nil {
		return nil, err
	}

	if opts.updateManifest && manifest != nil {
		if err := updateManifestFile(ctx, module, manifest, contractEndpoints); err != nil {
			return nil, fmt.Errorf("cannot update %s: %w", composition.PackageManifestFileName, err)
		}
		if err := composition.ValidatePackageAPIContracts(module.Dir(), manifest, catalog); err != nil {
			return nil, err
		}
	}

	return catalog, nil
}

// resolvePackageIdentity returns the catalog's Package/Version and, when the
// module has one, its package manifest. A module without a manifest is not
// packageable yet, so it falls back to a synthetic identity and a warning
// instead of failing the whole export.
func resolvePackageIdentity(module *resources.Module) (string, string, *composition.PackageManifest, error) {
	manifest, err := composition.LoadPackageManifest(module.Dir())
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			cli.Warning("module %s has no %s; it is not packageable yet", module.Name, composition.PackageManifestFileName)
			return "codefly/" + module.Name, "0.0.0", nil, nil
		}
		return "", "", nil, err
	}
	return manifest.ID, manifest.Version, manifest, nil
}

// writeEndpointContract writes one endpoint's contract files and returns its
// catalog entry.
func writeEndpointContract(ctx context.Context, module *resources.Module, service *resources.Service, endpoint *basev0.Endpoint, opts generateOptions) (*composition.APIContractEndpoint, error) {
	physicalDir := filepath.Join(opts.writeDir, service.Name, endpoint.Name)
	canonicalDir := filepath.Join(opts.canonicalOutput, service.Name, endpoint.Name)
	if err := os.RemoveAll(physicalDir); err != nil {
		return nil, fmt.Errorf("cannot clear %s: %w", physicalDir, err)
	}
	if err := os.MkdirAll(physicalDir, 0o755); err != nil {
		return nil, err
	}

	if grpc := resources.IsGRPC(ctx, endpoint); grpc != nil {
		return writeGRPCContract(ctx, module, service, endpoint, grpc, physicalDir, canonicalDir)
	}
	if rest := resources.IsRest(ctx, endpoint); rest != nil {
		return writeRestContract(ctx, module, endpoint, rest, physicalDir, canonicalDir)
	}
	return nil, fmt.Errorf("endpoint %s reports neither a grpc nor a rest contract", endpoint.Name)
}

func writeGRPCContract(ctx context.Context, module *resources.Module, service *resources.Service, endpoint *basev0.Endpoint, grpc *basev0.GrpcAPI, physicalDir, canonicalDir string) (*composition.APIContractEndpoint, error) {
	protoDir := filepath.Join(service.Dir(), "proto")
	if ok, _ := shared.FileExists(ctx, filepath.Join(protoDir, "buf.yaml")); !ok {
		return nil, fmt.Errorf("service %s has no proto/buf.yaml; cannot build a descriptor set for endpoint %s", service.Name, endpoint.Name)
	}

	descriptorSet, err := buildDescriptorSet(ctx, protoDir)
	if err != nil {
		return nil, fmt.Errorf("cannot build descriptor set: %w", err)
	}

	contractPath := filepath.Join(physicalDir, "contract.binpb")
	if err = shared.WriteFileAtomic(ctx, contractPath, descriptorSet, 0o644); err != nil {
		return nil, err
	}
	if err = copyTree(protoDir, filepath.Join(physicalDir, "proto")); err != nil {
		return nil, fmt.Errorf("cannot copy proto sources: %w", err)
	}

	var set descriptorpb.FileDescriptorSet
	if err = googleproto.Unmarshal(descriptorSet, &set); err != nil {
		return nil, fmt.Errorf("cannot parse generated descriptor set: %w", err)
	}

	relPath, err := relativeContractPath(module, filepath.Join(canonicalDir, "contract.binpb"))
	if err != nil {
		return nil, err
	}

	return &composition.APIContractEndpoint{
		Service:  service.Name,
		Endpoint: endpoint.Name,
		API:      endpoint.Api,
		Kind:     composition.APIContractKindProtobuf,
		Package:  grpc.Package,
		Path:     relPath,
		Digest:   composition.APIContractDigest(descriptorSet),
		Services: composition.ProtobufServices(&set, grpc.Package),
	}, nil
}

func writeRestContract(ctx context.Context, module *resources.Module, endpoint *basev0.Endpoint, rest *basev0.RestAPI, physicalDir, canonicalDir string) (*composition.APIContractEndpoint, error) {
	if len(rest.Openapi) == 0 {
		return nil, fmt.Errorf("endpoint %s has no OpenAPI document", endpoint.Name)
	}
	contractPath := filepath.Join(physicalDir, "openapi.json")
	if err := shared.WriteFileAtomic(ctx, contractPath, rest.Openapi, 0o644); err != nil {
		return nil, err
	}

	title, err := openAPITitle(rest.Openapi)
	if err != nil {
		return nil, fmt.Errorf("cannot read OpenAPI info.title: %w", err)
	}

	var routes []composition.APIContractRoute
	for _, group := range rest.Groups {
		for _, route := range group.Routes {
			routes = append(routes, composition.APIContractRoute{
				Method: route.Method.String(),
				Path:   path.Join(group.Path, route.Path),
			})
		}
	}

	relPath, err := relativeContractPath(module, filepath.Join(canonicalDir, "openapi.json"))
	if err != nil {
		return nil, err
	}

	return &composition.APIContractEndpoint{
		Service:  endpoint.Service,
		Endpoint: endpoint.Name,
		API:      endpoint.Api,
		Kind:     composition.APIContractKindOpenAPI,
		Package:  title,
		Path:     relPath,
		Digest:   composition.APIContractDigest(rest.Openapi),
		Routes:   routes,
	}, nil
}

func openAPITitle(data []byte) (string, error) {
	var document struct {
		Info struct {
			Title string `json:"title"`
		} `json:"info"`
	}
	if err := json.Unmarshal(data, &document); err != nil {
		return "", err
	}
	if document.Info.Title == "" {
		return "", fmt.Errorf("missing info.title")
	}
	return document.Info.Title, nil
}

// relativeContractPath returns path relative to the module directory,
// slash-separated: the form the catalog and package manifest record.
func relativeContractPath(module *resources.Module, path string) (string, error) {
	rel, err := filepath.Rel(module.Dir(), path)
	if err != nil {
		return "", err
	}
	return filepath.ToSlash(rel), nil
}

func printContractLine(endpoint *composition.APIContractEndpoint) {
	switch endpoint.Kind {
	case composition.APIContractKindProtobuf:
		cli.Info("contracts: %s/%s  %s  %s  %d service(s)  %s", endpoint.Service, endpoint.Endpoint, endpoint.Kind, endpoint.Package, len(endpoint.Services), endpoint.Digest)
	case composition.APIContractKindOpenAPI:
		cli.Info("contracts: %s/%s  %s  %s  %d route(s)  %s", endpoint.Service, endpoint.Endpoint, endpoint.Kind, endpoint.Package, len(endpoint.Routes), endpoint.Digest)
	}
}

// buildDescriptorSet runs buf inside the proto companion to compile protoDir
// into a serialized descriptorpb.FileDescriptorSet, transitive imports
// included. It works from a temporary copy of protoDir so buf's dependency
// resolution never mutates the service's committed buf.lock.
func buildDescriptorSet(ctx context.Context, protoDir string) ([]byte, error) {
	if !runners.DockerEngineRunning(ctx) {
		return nil, fmt.Errorf("docker is not running; please start Docker first")
	}
	image, err := proto.CompanionImage(ctx)
	if err != nil {
		return nil, fmt.Errorf("cannot get companion image: %w", err)
	}

	tmpDir, err := os.MkdirTemp("", "codefly-contract-proto")
	if err != nil {
		return nil, err
	}
	defer func() { _ = os.RemoveAll(tmpDir) }()

	if err = copyTree(protoDir, tmpDir); err != nil {
		return nil, fmt.Errorf("cannot copy proto sources: %w", err)
	}

	name := fmt.Sprintf("contracts-%d", time.Now().UnixMilli())
	runner, err := runners.NewDockerEnvironment(ctx, image, tmpDir, name)
	if err != nil {
		return nil, fmt.Errorf("cannot create docker runner: %w", err)
	}
	runner.WithMount(tmpDir, "/workspace")
	runner.WithWorkDir("/workspace")
	runner.WithPause()
	defer func() {
		cleanupCtx := context.WithoutCancel(ctx)
		_ = runner.Shutdown(cleanupCtx)
	}()

	if err = runner.Init(ctx); err != nil {
		return nil, fmt.Errorf("cannot init runner: %w", err)
	}

	depProc, err := runner.NewProcess("buf", "dep", "update")
	if err != nil {
		return nil, fmt.Errorf("cannot create process: %w", err)
	}
	if err = depProc.Run(ctx); err != nil {
		return nil, fmt.Errorf("cannot update buf dependencies: %w", err)
	}

	const descriptorFile = ".codefly-contract.binpb"
	buildProc, err := runner.NewProcess("buf", "build", "--as-file-descriptor-set", "-o", "/workspace/"+descriptorFile)
	if err != nil {
		return nil, fmt.Errorf("cannot create process: %w", err)
	}
	if err = buildProc.Run(ctx); err != nil {
		return nil, fmt.Errorf("cannot build descriptor set: %w", err)
	}

	return os.ReadFile(filepath.Join(tmpDir, descriptorFile))
}

// copyTree copies the file tree rooted at src into dst, creating dst as
// needed.
func copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(p string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(p) //nolint:gosec // p is walked from src, a service's own committed proto directory
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644) //nolint:gosec
	})
}

// runContractsCheck regenerates contracts into a throwaway directory and
// diffs them against output, without writing anything real.
func runContractsCheck(ctx context.Context, workspace *resources.Workspace, module *resources.Module, output string) error {
	tempDir, err := os.MkdirTemp("", "codefly-contracts-check")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(tempDir) }()

	if _, err = generateContracts(ctx, workspace, module, generateOptions{
		canonicalOutput: output,
		writeDir:        tempDir,
		updateManifest:  false,
	}); err != nil {
		return err
	}

	diffs, err := diffTrees(tempDir, output)
	if err != nil {
		return err
	}
	if len(diffs) == 0 {
		cli.Header(1, "Contracts are up to date")
		return nil
	}
	cli.Warning("Contracts are out of date:")
	for _, d := range diffs {
		cli.Info("  %s", d)
	}
	return fmt.Errorf("generated contracts differ from %s (%d file(s)); run `codefly generate contracts` to update", output, len(diffs))
}

// diffTrees returns the slash-separated, sorted set of relative paths whose
// content (or presence) differs between the two directory trees.
func diffTrees(generated, existing string) ([]string, error) {
	generatedFiles, err := listRelativeFiles(generated)
	if err != nil {
		return nil, err
	}
	existingFiles, err := listRelativeFiles(existing)
	if err != nil {
		return nil, err
	}

	seen := map[string]struct{}{}
	for f := range generatedFiles {
		seen[f] = struct{}{}
	}
	for f := range existingFiles {
		seen[f] = struct{}{}
	}

	var diffs []string
	for f := range seen {
		a, okA := generatedFiles[f]
		b, okB := existingFiles[f]
		if okA != okB || !bytes.Equal(a, b) {
			diffs = append(diffs, f)
		}
	}
	sort.Strings(diffs)
	return diffs, nil
}

func listRelativeFiles(root string) (map[string][]byte, error) {
	files := map[string][]byte{}
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return files, nil
		}
		return nil, err
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("%s is not a directory", root)
	}
	err = filepath.WalkDir(root, func(p string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(root, p)
		if relErr != nil {
			return relErr
		}
		data, readErr := os.ReadFile(p) //nolint:gosec // p is walked from root, a generated-contracts directory this command owns
		if readErr != nil {
			return readErr
		}
		files[filepath.ToSlash(rel)] = data
		return nil
	})
	return files, err
}

// updateManifestFile rewrites module.package.codefly.yaml's
// services[*].api-contracts for the services present in contractEndpoints,
// preserving every other byte of the file (comments, key order, unrelated
// content) via a yaml.Node round-trip instead of a struct re-marshal.
func updateManifestFile(ctx context.Context, module *resources.Module, manifest *composition.PackageManifest, contractEndpoints []composition.APIContractEndpoint) error {
	entries := map[string][]composition.ProvidedAPIContract{}
	for i := range contractEndpoints {
		endpoint := &contractEndpoints[i]
		entries[endpoint.Service] = append(entries[endpoint.Service], composition.ProvidedAPIContract{
			Endpoint: endpoint.Endpoint,
			Kind:     endpoint.Kind,
			Package:  endpoint.Package,
			Path:     endpoint.Path,
			Digest:   endpoint.Digest,
		})
	}
	if len(entries) == 0 {
		return nil
	}

	file := filepath.Join(module.Dir(), composition.PackageManifestFileName)
	content, err := os.ReadFile(file)
	if err != nil {
		return err
	}
	updated, err := updatePackageManifestAPIContracts(content, entries)
	if err != nil {
		return err
	}
	if err := shared.WriteFileAtomic(ctx, file, updated, 0o644); err != nil {
		return err
	}
	manifest.Services = mergeAPIContracts(manifest.Services, entries)
	return nil
}

func mergeAPIContracts(services []composition.ProvidedService, entries map[string][]composition.ProvidedAPIContract) []composition.ProvidedService {
	for i := range services {
		if contracts, ok := entries[services[i].Name]; ok {
			services[i].APIContracts = contracts
		}
	}
	return services
}

// updatePackageManifestAPIContracts sets services[name].api-contracts for
// each service in entries to its given list, replacing whatever was there.
// Every other node in the document — comments, key order, unrelated fields —
// is left untouched: the document is parsed into a yaml.Node tree, mutated in
// place, and re-encoded, never reconstructed from a Go struct.
func updatePackageManifestAPIContracts(content []byte, entries map[string][]composition.ProvidedAPIContract) ([]byte, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(content, &doc); err != nil {
		return nil, fmt.Errorf("cannot parse package manifest: %w", err)
	}
	if len(doc.Content) == 0 {
		return nil, fmt.Errorf("empty package manifest")
	}
	root := doc.Content[0]
	services := mappingValue(root, "services")
	if services == nil || services.Kind != yaml.SequenceNode {
		return nil, fmt.Errorf("package manifest has no services list")
	}

	names := make([]string, 0, len(entries))
	for name := range entries {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		var target *yaml.Node
		for _, item := range services.Content {
			if nameNode := mappingValue(item, "name"); nameNode != nil && nameNode.Value == name {
				target = item
				break
			}
		}
		if target == nil {
			return nil, fmt.Errorf("package manifest has no service %q", name)
		}
		setMappingValue(target, "api-contracts", buildAPIContractsNode(entries[name]))
	}

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func mappingValue(node *yaml.Node, key string) *yaml.Node {
	if node == nil || node.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1]
		}
	}
	return nil
}

func setMappingValue(node *yaml.Node, key string, value *yaml.Node) {
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			node.Content[i+1] = value
			return
		}
	}
	node.Content = append(node.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: yamlStringTag, Value: key}, value)
}

func buildAPIContractsNode(contracts []composition.ProvidedAPIContract) *yaml.Node {
	seq := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
	for _, contract := range contracts {
		item := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
		appendScalarField(item, "endpoint", contract.Endpoint)
		appendScalarField(item, "kind", contract.Kind)
		appendScalarField(item, "package", contract.Package)
		appendScalarField(item, "path", contract.Path)
		appendScalarField(item, "digest", contract.Digest)
		seq.Content = append(seq.Content, item)
	}
	return seq
}

func appendScalarField(node *yaml.Node, key, value string) {
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Tag: yamlStringTag, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Tag: yamlStringTag, Value: value},
	)
}
