package generate

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"time"

	"github.com/codefly-dev/cli/cmd/common"
	"github.com/codefly-dev/cli/pkg/cli"
	"github.com/codefly-dev/cli/pkg/environments"
	"github.com/codefly-dev/cli/pkg/remotenetwork"
	runnablespkg "github.com/codefly-dev/cli/pkg/runnables"
	"github.com/codefly-dev/core/composition"
	"github.com/codefly-dev/core/configurations"
	basev0 "github.com/codefly-dev/core/generated/go/codefly/base/v0"
	runnablev0 "github.com/codefly-dev/core/generated/go/codefly/runnable/v0"
	"github.com/codefly-dev/core/network"
	"github.com/codefly-dev/core/resources"
	corerunnable "github.com/codefly-dev/core/runnable"
	"github.com/codefly-dev/core/standards"
	"github.com/spf13/cobra"
)

// RunnableBindingsGroup is the workspace configuration group the prepared
// bindings are written to. A service that installs derived operations (an
// orchestrator's worker) declares it as a workspace configuration dependency;
// no module names another to receive them.
const RunnableBindingsGroup = "runnable-bindings"

// runnableBindingsFileHeader marks the file as generated output.
const runnableBindingsFileHeader = "# Generated by `codefly generate runnable-bindings`. DO NOT EDIT: regenerate.\n"

var (
	runnableBindingsEnv   string
	runnableBindingsCheck bool
)

// RunnableBindingsCmd prepares, for one environment, the binding of every
// operation the workspace's modules derived: the operation, where one call is
// sent as that environment resolves it, the bounded contract with its digest,
// and the policy and authority the owner declared.
var RunnableBindingsCmd = &cobra.Command{
	Use:   "runnable-bindings",
	Short: "Prepare the binding of every derived Runnable operation for an environment",
	Long: `Prepare the binding of every Runnable operation the workspace's modules derived
(contracts/runnables/index.json, written by ` + "`codefly generate runnables`" + `), for
one environment, and write them as the workspace configuration group
` + RunnableBindingsGroup + `.

For each derived operation the value is one JSON document
(` + corerunnable.PreparedSchemaV3 + `):

  operation        the owner coordinates, and the operation as the owner spells
                   it: /pkg.Service/Method, or "POST /path"
  call             where one call is sent: the resolved base URL, and a typed
                   route — connect (the procedure, POSTed as JSON on the owner's
                   Connect endpoint) or rest (the owner's own verb and path)
  contract         the bounded input and output schema
  contract_digest  sha256 over that contract, so an owner that republishes a
                   changed contract is refused rather than called with a payload
                   shaped for the one it used to publish
  policy           the execution policy and Work Context authority the owner
                   declared, with required scope slots resolved from this
                   environment's runnable-scope-selections

An owner is called with JSON, so no protobuf descriptor is delivered to anyone.
A gRPC owner is therefore called on its **Connect** endpoint: a service that
publishes a runnable-marked method and declares no connect endpoint is refused
here, by name, rather than at a call.
An operation published directly on a Connect endpoint uses that endpoint.

The address is resolved, never configured: it is the one a run or a render of
the same environment gives the owner. A service that installs derived
operations declares ` + RunnableBindingsGroup + ` as a workspace configuration dependency and
receives them like any other group, so the installer names no owner module.

In workspace.codefly.yaml, environments[].runnable-scope-selections maps each
binding key (MODULE__OPERATION) to Core ScopeSelection messages: slot, invoke,
and lookup. Every required slot needs exact resource kinds, actions and ids;
missing selections, wildcards and overlapping kinds are refused. Tool exposure
is carried from the owner. See docs/runnable.md for the selection YAML.

The output is configurations/<profile>/` + RunnableBindingsGroup + `.env in the workspace, for the
environment's first configuration profile. --check regenerates in memory and
exits non-zero when the file differs, including after a scope selection changes.

Examples:
  codefly generate runnable-bindings
  codefly generate runnable-bindings --env staging
  codefly generate runnable-bindings --env staging --check`,
	Args: cobra.NoArgs,
	RunE: func(_ *cobra.Command, _ []string) error {
		ctx, done := common.NewContext()
		defer done()
		ctx, stop := common.SignalContext(ctx)
		defer stop()

		workspace, err := common.LoadWorkspace(ctx)
		if err != nil {
			return err
		}
		env, err := environments.Select(workspace, runnableBindingsEnv)
		if err != nil {
			return err
		}
		content, count, err := prepareRunnableBindings(ctx, workspace, env)
		if err != nil {
			return err
		}
		profile, err := env.ConfigurationProfileName()
		if err != nil {
			return err
		}
		target := filepath.Join(workspace.Dir(), "configurations", profile, RunnableBindingsGroup+".env")
		if runnableBindingsCheck {
			existing, err := os.ReadFile(target)
			if err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			if !bytes.Equal(existing, content) {
				return fmt.Errorf("%s is out of date: run `codefly generate runnable-bindings --env %s`", target, env.Name)
			}
			cli.Info("runnable-bindings: %s is current (%d operation(s))", target, count)
			return nil
		}
		if count == 0 {
			if err := os.Remove(target); err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			cli.Info("runnable-bindings: no module derives an operation; nothing to bind")
			return nil
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, content, 0o600); err != nil {
			return err
		}
		cli.Header(1, "Bound %d runnable operation(s) for %s in %s", count, env.Name, target)
		return nil
	},
}

func init() {
	RunnableBindingsCmd.Flags().StringVar(&runnableBindingsEnv, "env", "local", "environment supplying resolved addresses and runnable-scope-selections")
	RunnableBindingsCmd.Flags().BoolVar(&runnableBindingsCheck, "check", false, "do not write; exit 1 if the on-disk file differs from what would be generated")
}

// prepareRunnableBindings walks every module of the workspace and prepares a
// binding for each operation it derived, returning the configuration file.
func prepareRunnableBindings(ctx context.Context, workspace *resources.Workspace, env *environments.Environment) ([]byte, int, error) {
	modules, err := workspace.LoadModules(ctx)
	if err != nil {
		return nil, 0, err
	}
	resolver, err := newEndpointResolver(ctx, workspace, env)
	if err != nil {
		return nil, 0, err
	}
	lines := map[string]string{}
	for _, module := range modules {
		derived, err := runnablespkg.LoadDerivedOperations(module.Dir())
		if err != nil {
			return nil, 0, fmt.Errorf("module %s: %w", module.Name, err)
		}
		for i := range derived {
			operation := &derived[i]
			prepared, err := prepareRunnable(ctx, module, operation, resolver)
			if err != nil {
				return nil, 0, fmt.Errorf("module %s operation %s: %w", module.Name, operation.Entry.Name, err)
			}
			// EncodePrepared fills the schema and the contract digest and holds
			// the value to the rules its reader applies, so what is written is
			// what installs.
			value, err := corerunnable.EncodePrepared(prepared)
			if err != nil {
				return nil, 0, fmt.Errorf("module %s operation %s: %w", module.Name, operation.Entry.Name, err)
			}
			key := RunnableBindingKey(module.Name, operation.Entry.Name)
			if _, taken := lines[key]; taken {
				return nil, 0, fmt.Errorf("two operations bind under key %s", key)
			}
			lines[key] = string(value)
		}
	}
	for _, key := range sortedKeys(env.RunnableScopeSelections) {
		if _, bound := lines[key]; !bound {
			return nil, 0, fmt.Errorf("environment %s runnable-scope-selections[%s] names no derived operation", env.Name, key)
		}
	}
	count := len(lines)
	keys := make([]string, 0, len(lines))
	for key := range lines {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString(runnableBindingsFileHeader)
	for _, key := range keys {
		out.WriteString(key + "=" + lines[key] + "\n")
	}
	return []byte(out.String()), count, nil
}

// RunnableBindingKey is the configuration key an operation is bound under:
// its module and its derived name, upper-cased with every other character an
// underscore, so the SDK's workspace-value lookup finds it.
func RunnableBindingKey(module, name string) string {
	var key strings.Builder
	for _, r := range strings.ToUpper(module + "__" + name) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			key.WriteRune(r)
			continue
		}
		key.WriteByte('_')
	}
	return key.String()
}

// prepareRunnable prepares one derived operation for the environment the
// resolver answers for.
func prepareRunnable(ctx context.Context, module *resources.Module, operation *runnablespkg.Derived, resolver *endpointResolver) (*runnablev0.PreparedBinding, error) {
	pkg := operation.Package
	if len(pkg.GetServiceOperations()) != 1 {
		return nil, fmt.Errorf("a derived package carries exactly one service operation, found %d", len(pkg.GetServiceOperations()))
	}
	descriptor := pkg.GetServiceOperations()[0]
	call, kind, err := resolver.callTarget(ctx, module, operation.Entry.Service, operation.Entry.Endpoint, descriptor.GetOperation(), operation.Operation.LookupMethod)
	if err != nil {
		return nil, err
	}
	if err = verifyPublishedContract(module, operation.Entry.Service, operation.Entry.Endpoint, kind); err != nil {
		return nil, err
	}
	codes := corerunnable.GRPCStatusNames
	if kind == composition.APIContractKindOpenAPI {
		codes = corerunnable.HTTPStatusCodes
	}
	spec, err := operationSpec(operation.Operation, descriptor.GetOperation(), codes)
	if err != nil {
		return nil, err
	}
	key := RunnableBindingKey(module.Name, operation.Entry.Name)
	resolved, err := spec.ResolveScopeSlots(resolver.env.RunnableScopeSelections[key])
	if err != nil {
		return nil, fmt.Errorf("environment %s runnable-scope-selections[%s] in workspace.codefly.yaml: %w", resolver.env.Name, key, err)
	}
	return &runnablev0.PreparedBinding{
		Operation: &runnablev0.PreparedOperation{
			Module:   descriptor.GetModule(),
			Service:  descriptor.GetName(),
			Endpoint: descriptor.GetEndpoint(),
			Spelling: descriptor.GetOperation(),
		},
		Call:     call,
		Contract: pkg.GetContract(),
		Policy:   resolved.Policy(),
	}, nil
}

// operationSpec reads the derived document back into Core's spec so Core can
// resolve its slots once and write the resulting policy with Policy(). The
// document round-trip test holds both conversions to every Operation field.
func operationSpec(declared *runnablespkg.Operation, spelling string, codes corerunnable.CodeVocabulary) (*corerunnable.OperationSpec, error) {
	if declared == nil {
		return nil, errors.New("the operation declares no execution policy")
	}
	durations := map[string]time.Duration{}
	for field, spelled := range map[string]string{
		"attempt_timeout": declared.AttemptTimeout,
		"total_timeout":   declared.TotalTimeout,
		"backoff":         declared.Backoff,
	} {
		parsed, err := time.ParseDuration(spelled)
		if err != nil {
			return nil, fmt.Errorf("%s %q is not a duration: %w", field, spelled, err)
		}
		durations[field] = parsed
	}
	completion, named := basev0.RunnableExecution_Completion_value[declared.Completion]
	if !named || basev0.RunnableExecution_Completion(completion) == basev0.RunnableExecution_COMPLETION_UNKNOWN {
		return nil, fmt.Errorf("completion %q is not a completion mode; %s and %s are the two",
			declared.Completion, basev0.RunnableExecution_COMPLETION_CALL, basev0.RunnableExecution_COMPLETION_SUBMIT)
	}
	return &corerunnable.OperationSpec{
		Method:             spelling,
		Codes:              codes,
		AttemptTimeout:     durations["attempt_timeout"],
		TotalTimeout:       durations["total_timeout"],
		MaxAttempts:        declared.MaxAttempts,
		Backoff:            durations["backoff"],
		RetryableCodes:     declared.RetryableCodes,
		Audience:           declared.Audience,
		InvokeScopes:       preparedScopes(declared.InvokeScopes),
		LookupScopes:       preparedScopes(declared.LookupScopes),
		LookupMethod:       declared.LookupMethod,
		MaxInputBytes:      declared.MaxInputBytes,
		MaxOutputBytes:     declared.MaxOutputBytes,
		Completion:         basev0.RunnableExecution_Completion(completion),
		Tool:               declared.Tool,
		RequiredScopeSlots: declared.RequiredScopeSlots,
	}, nil
}

func preparedScopes(declared []runnablespkg.Scope) []*basev0.WorkScopeV1 {
	scopes := make([]*basev0.WorkScopeV1, 0, len(declared))
	for _, scope := range declared {
		scopes = append(scopes, &basev0.WorkScopeV1{ResourceKind: scope.ResourceKind, Actions: scope.Actions, ResourceIds: scope.ResourceIDs})
	}
	return scopes
}

// verifyPublishedContract holds the owner's published contract to the bytes the
// API contract catalog recorded for it. A prepared value states the digest of
// the bounded contract derived from it, so a catalog that no longer describes
// what is on disk means the derivation the value carries was read from
// something nobody published.
func verifyPublishedContract(module *resources.Module, service, endpoint, kind string) error {
	catalog, err := composition.LoadAPIContractCatalog(module.Dir())
	if err != nil {
		return err
	}
	var published *composition.APIContractEndpoint
	for i := range catalog.Endpoints {
		candidate := &catalog.Endpoints[i]
		if candidate.Service == service && candidate.Endpoint == endpoint && candidate.Kind == kind {
			published = candidate
		}
	}
	if published == nil {
		return fmt.Errorf("%s/%s publishes no %s contract: run `codefly generate contracts`", service, endpoint, kind)
	}
	raw, err := os.ReadFile(filepath.Join(module.Dir(), filepath.FromSlash(published.Path)))
	if err != nil {
		return err
	}
	if digest := composition.APIContractDigest(raw); digest != published.Digest {
		return fmt.Errorf("%s/%s: %s is %s but the contract catalog records %s: run `codefly generate contracts`", service, endpoint, published.Path, digest, published.Digest)
	}
	return nil
}

// endpointResolver resolves an owner endpoint the way a run or a render of the
// environment does: the native address locally, the in-cluster Service in a
// Kubernetes environment.
type endpointResolver struct {
	workspace *resources.Workspace
	env       *environments.Environment
	remote    *remotenetwork.RemoteManager
}

func newEndpointResolver(ctx context.Context, workspace *resources.Workspace, env *environments.Environment) (*endpointResolver, error) {
	resolver := &endpointResolver{workspace: workspace, env: env}
	if env.Local() {
		return resolver, nil
	}
	manager, err := configurations.NewManager(ctx, workspace)
	if err != nil {
		return nil, err
	}
	reader, err := configurations.NewConfigurationLocalReader(ctx, workspace)
	if err != nil {
		return nil, err
	}
	manager.WithLoader(reader)
	if resolver.remote, err = remotenetwork.NewRemoteManager(ctx, manager); err != nil {
		return nil, err
	}
	return resolver, nil
}

// callTarget answers where a JSON call to one operation is sent, and the kind
// of contract its owner publishes for it.
//
// A gRPC owner is called on its **Connect** endpoint: the gRPC port carries no
// JSON call, and an owner's descriptors are delivered to nobody any more. A
// service that publishes a runnable-marked method and declares no connect
// endpoint is refused here rather than at a call — the address a caller would
// otherwise be handed is one that answers nothing it can send.
func (r *endpointResolver) callTarget(ctx context.Context, module *resources.Module, serviceName, publishedName, spelling, lookup string) (*runnablev0.PreparedCall, string, error) {
	identity, endpoints, err := r.load(ctx, module, serviceName)
	if err != nil {
		return nil, "", err
	}
	published := endpointNamed(endpoints, publishedName)
	if published == nil {
		return nil, "", fmt.Errorf("service %s/%s declares no endpoint %s", module.Name, serviceName, publishedName)
	}
	switch published.GetApi() {
	case standards.GRPC, standards.CONNECT:
		connect, err := servedConnectEndpoint(module, serviceName, published, endpoints, spelling, lookup)
		if err != nil {
			return nil, "", err
		}
		address, err := r.address(ctx, identity, endpoints, connect)
		if err != nil {
			return nil, "", err
		}
		return &runnablev0.PreparedCall{
			Address: address,
			Route:   &runnablev0.PreparedCall_Connect{Connect: &runnablev0.ConnectProcedure{Procedure: spelling}},
		}, composition.APIContractKindProtobuf, nil
	case standards.REST:
		address, err := r.address(ctx, identity, endpoints, published)
		if err != nil {
			return nil, "", err
		}
		verb, path, spelled := strings.Cut(spelling, " ")
		if !spelled {
			return nil, "", fmt.Errorf("%s/%s publishes %q, which is not a route a REST owner is called on", module.Name, serviceName, spelling)
		}
		return &runnablev0.PreparedCall{
			Address: address,
			Route:   &runnablev0.PreparedCall_Rest{Rest: &runnablev0.HTTPRoute{Verb: verb, Path: path}},
		}, composition.APIContractKindOpenAPI, nil
	default:
		return nil, "", fmt.Errorf("%s/%s/%s is a %s endpoint, and a derived operation is called over %s, %s or %s",
			module.Name, serviceName, publishedName, published.GetApi(), standards.GRPC, standards.CONNECT, standards.REST)
	}
}

func endpointNamed(endpoints []*basev0.Endpoint, name string) *basev0.Endpoint {
	for _, candidate := range endpoints {
		if candidate.GetName() == name {
			return candidate
		}
	}
	return nil
}

// Select from the published served surface, including the paired lookup.
// The first declared Connect listener is not evidence that it serves a method.
func servedConnectEndpoint(module *resources.Module, service string, published *basev0.Endpoint, endpoints []*basev0.Endpoint, spelling, lookup string) (*basev0.Endpoint, error) {
	catalog, err := composition.LoadAPIContractCatalog(module.Dir())
	if err != nil {
		return nil, err
	}
	var candidates, eligible []string
	var selected *basev0.Endpoint
	for _, endpoint := range endpoints {
		if endpoint.GetApi() != standards.CONNECT || (published.GetApi() == standards.CONNECT && endpoint.Name != published.Name) {
			continue
		}
		candidates = append(candidates, endpoint.Name)
		var serves, servesLookup bool
		for i := range catalog.Endpoints {
			entry := &catalog.Endpoints[i]
			if entry.Service != service || entry.Endpoint != endpoint.Name || entry.API != standards.CONNECT || entry.Kind != composition.APIContractKindProtobuf {
				continue
			}
			for _, svc := range entry.Services {
				serves = serves || slices.Contains(svc.Procedures, spelling)
				servesLookup = servesLookup || slices.Contains(svc.Procedures, lookup)
			}
		}
		if !serves || (lookup != "" && !servesLookup) {
			continue
		}
		if err := verifyPublishedContract(module, service, endpoint.Name, composition.APIContractKindProtobuf); err != nil {
			return nil, err
		}
		eligible = append(eligible, endpoint.Name)
		selected = endpoint
	}
	sort.Strings(candidates)
	sort.Strings(eligible)
	if len(eligible) == 0 {
		return nil, fmt.Errorf("%s/%s/%s: no connect endpoint among %v publishes served procedure %s and lookup %q in contracts/api/catalog.codefly.json; export the called endpoint in module.codefly.yaml and run `codefly generate contracts %s`; see docs/commands.md#generate-contracts", module.Name, service, published.Name, candidates, spelling, lookup, module.Name)
	}
	if len(eligible) > 1 {
		return nil, fmt.Errorf("%s/%s/%s: ambiguous connect endpoints %v serving %s and lookup %q; derive the operation under the intended Connect endpoint", module.Name, service, published.Name, eligible, spelling, lookup)
	}
	return selected, nil
}

func (r *endpointResolver) load(ctx context.Context, module *resources.Module, serviceName string) (*resources.ServiceIdentity, []*basev0.Endpoint, error) {
	service, err := module.LoadServiceFromName(ctx, serviceName)
	if err != nil {
		return nil, nil, err
	}
	identity, err := service.Identity()
	if err != nil {
		return nil, nil, err
	}
	endpoints, err := service.LoadEndpoints(ctx)
	if err != nil {
		return nil, nil, err
	}
	return identity, endpoints, nil
}

// address is the endpoint's address as a run or a render of this environment
// gives it: the native address locally, the in-cluster Service in a Kubernetes
// environment. An HTTP-based endpoint resolves to a base URL, which is what a
// prepared call carries.
func (r *endpointResolver) address(ctx context.Context, identity *resources.ServiceIdentity, endpoints []*basev0.Endpoint, endpoint *basev0.Endpoint) (string, error) {
	if r.env.Local() {
		instance := network.NativeFor(ctx, r.workspace.Name, identity.Module, identity.Name, r.env.NamingScope, endpoint)
		if instance == nil {
			return "", fmt.Errorf("no native address for %s/%s/%s", identity.Module, identity.Name, endpoint.GetName())
		}
		return instance.GetAddress(), nil
	}
	mappings, err := r.remote.GenerateNetworkMappings(ctx, r.env, r.workspace, identity, endpoints)
	if err != nil {
		return "", err
	}
	for _, mapping := range mappings {
		if mapping.GetEndpoint().GetName() != endpoint.GetName() {
			continue
		}
		container := resources.FilterNetworkInstance(ctx, mapping.GetInstances(), resources.NewContainerNetworkAccess())
		if container == nil {
			return "", fmt.Errorf("%s/%s/%s resolves no in-cluster address in %s", identity.Module, identity.Name, endpoint.GetName(), r.env.Name)
		}
		return container.GetAddress(), nil
	}
	return "", fmt.Errorf("%s/%s/%s resolves no mapping in %s", identity.Module, identity.Name, endpoint.GetName(), r.env.Name)
}
