package generate

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/codefly-dev/cli/cmd/common"
	"github.com/codefly-dev/cli/pkg/cli"
	"github.com/codefly-dev/cli/pkg/environments"
	"github.com/codefly-dev/cli/pkg/remotenetwork"
	runnablespkg "github.com/codefly-dev/cli/pkg/runnables"
	"github.com/codefly-dev/core/composition"
	"github.com/codefly-dev/core/configurations"
	basev0 "github.com/codefly-dev/core/generated/go/codefly/base/v0"
	"github.com/codefly-dev/core/network"
	"github.com/codefly-dev/core/resources"
	corerunnable "github.com/codefly-dev/core/runnable"
	"github.com/spf13/cobra"
	googleproto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

// RunnableBindingsGroup is the workspace configuration group the prepared
// bindings are written to. A service that installs derived operations (an
// orchestrator's worker) declares it as a workspace configuration dependency;
// no module names another to receive them.
const RunnableBindingsGroup = "runnable-bindings"

// runnableBindingsFileHeader marks the file as generated output.
const runnableBindingsFileHeader = "# Generated by `codefly generate runnable-bindings`. DO NOT EDIT: regenerate.\n"

var (
	runnableBindingsEnv   string
	runnableBindingsCheck bool
)

// RunnableBindingsCmd prepares, for one environment, the binding of every
// operation the workspace's modules derived: the package, its binding to the
// owner endpoint as that environment resolves it, the execution policy, and
// the owner's descriptors the call is made from.
var RunnableBindingsCmd = &cobra.Command{
	Use:   "runnable-bindings",
	Short: "Prepare the binding of every derived Runnable operation for an environment",
	Long: `Prepare the binding of every Runnable operation the workspace's modules derived
(contracts/runnables/index.json, written by ` + "`codefly generate runnables`" + `), for
one environment, and write them as the workspace configuration group
` + RunnableBindingsGroup + `.

For each derived operation the value is one JSON document:

  package      the canonical RunnablePackage
  binding      the RunnableBinding: the package installed on the SERVICE facility,
               targeting the owner endpoint at the address this environment
               resolves (the native address locally, the in-cluster Service in a
               Kubernetes environment); prepared and verified by core
  operation    the execution policy and authority the method declared
  descriptors  the owner's FileDescriptorSet for the method's file and its imports
               (base64), which a generic caller resolves the method in

The address is resolved, never configured: it is the one a run or a render of
the same environment gives the owner. A service that installs derived
operations declares ` + RunnableBindingsGroup + ` as a workspace configuration dependency and
receives them like any other group, so the installer names no owner module.

The output is configurations/<profile>/` + RunnableBindingsGroup + `.env in the workspace, for the
environment's first configuration profile. --check regenerates in memory and
exits non-zero when the file differs.

Examples:
  codefly generate runnable-bindings
  codefly generate runnable-bindings --env staging
  codefly generate runnable-bindings --env staging --check`,
	Args: cobra.NoArgs,
	RunE: func(_ *cobra.Command, _ []string) error {
		ctx, done := common.NewContext()
		defer done()
		ctx, stop := common.SignalContext(ctx)
		defer stop()

		workspace, err := common.LoadWorkspace(ctx)
		if err != nil {
			return err
		}
		env, err := environments.Select(workspace, runnableBindingsEnv)
		if err != nil {
			return err
		}
		content, count, err := prepareRunnableBindings(ctx, workspace, env)
		if err != nil {
			return err
		}
		profile, err := env.ConfigurationProfileName()
		if err != nil {
			return err
		}
		target := filepath.Join(workspace.Dir(), "configurations", profile, RunnableBindingsGroup+".env")
		if runnableBindingsCheck {
			existing, err := os.ReadFile(target)
			if err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			if !bytes.Equal(existing, content) {
				return fmt.Errorf("%s is out of date: run `codefly generate runnable-bindings --env %s`", target, env.Name)
			}
			cli.Info("runnable-bindings: %s is current (%d operation(s))", target, count)
			return nil
		}
		if count == 0 {
			if err := os.Remove(target); err != nil && !errors.Is(err, os.ErrNotExist) {
				return err
			}
			cli.Info("runnable-bindings: no module derives an operation; nothing to bind")
			return nil
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, content, 0o600); err != nil {
			return err
		}
		cli.Header(1, "Bound %d runnable operation(s) for %s in %s", count, env.Name, target)
		return nil
	},
}

func init() {
	RunnableBindingsCmd.Flags().StringVar(&runnableBindingsEnv, "env", "local", "environment whose resolved addresses the bindings target")
	RunnableBindingsCmd.Flags().BoolVar(&runnableBindingsCheck, "check", false, "do not write; exit 1 if the on-disk file differs from what would be generated")
}

// PreparedRunnable is one derived operation installed for an environment.
type PreparedRunnable struct {
	Package     json.RawMessage         `json:"package"`
	Binding     json.RawMessage         `json:"binding"`
	Operation   *runnablespkg.Operation `json:"operation"`
	Descriptors string                  `json:"descriptors"`
}

// prepareRunnableBindings walks every module of the workspace and prepares a
// binding for each operation it derived, returning the configuration file.
func prepareRunnableBindings(ctx context.Context, workspace *resources.Workspace, env *environments.Environment) ([]byte, int, error) {
	modules, err := workspace.LoadModules(ctx)
	if err != nil {
		return nil, 0, err
	}
	resolver, err := newEndpointResolver(ctx, workspace, env)
	if err != nil {
		return nil, 0, err
	}
	lines := map[string]string{}
	for _, module := range modules {
		derived, err := runnablespkg.LoadDerivedOperations(module.Dir())
		if err != nil {
			return nil, 0, fmt.Errorf("module %s: %w", module.Name, err)
		}
		for i := range derived {
			operation := &derived[i]
			prepared, err := prepareRunnable(ctx, module, operation, resolver, env.Name)
			if err != nil {
				return nil, 0, fmt.Errorf("module %s operation %s: %w", module.Name, operation.Entry.Name, err)
			}
			value, err := json.Marshal(prepared)
			if err != nil {
				return nil, 0, err
			}
			key := RunnableBindingKey(module.Name, operation.Entry.Name)
			if _, taken := lines[key]; taken {
				return nil, 0, fmt.Errorf("two operations bind under key %s", key)
			}
			lines[key] = string(value)
		}
	}
	keys := make([]string, 0, len(lines))
	for key := range lines {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	out.WriteString(runnableBindingsFileHeader)
	for _, key := range keys {
		out.WriteString(key + "=" + lines[key] + "\n")
	}
	return []byte(out.String()), len(keys), nil
}

// RunnableBindingKey is the configuration key an operation is bound under:
// its module and its derived name, upper-cased with every other character an
// underscore, so the SDK's workspace-value lookup finds it.
func RunnableBindingKey(module, name string) string {
	var key strings.Builder
	for _, r := range strings.ToUpper(module + "__" + name) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			key.WriteRune(r)
			continue
		}
		key.WriteByte('_')
	}
	return key.String()
}

func prepareRunnable(ctx context.Context, module *resources.Module, operation *runnablespkg.Derived, resolver *endpointResolver, envName string) (*PreparedRunnable, error) {
	pkg := operation.Package
	if len(pkg.GetServiceOperations()) != 1 {
		return nil, fmt.Errorf("a derived package carries exactly one service operation, found %d", len(pkg.GetServiceOperations()))
	}
	descriptor := pkg.GetServiceOperations()[0]
	mapping, err := resolver.resolve(ctx, module, operation.Entry.Service, operation.Entry.Endpoint)
	if err != nil {
		return nil, err
	}
	target := &basev0.RunnableTarget{
		Schema:      corerunnable.TargetSchemaV1,
		Environment: envName,
		Coordinates: &basev0.RunnableTarget_Service{Service: &basev0.RunnableServiceTarget{Endpoint: mapping}},
	}
	target.Revision, err = targetRevision(pkg.GetDigest(), mapping)
	if err != nil {
		return nil, err
	}
	binding, err := corerunnable.PrepareBinding(&basev0.RunnableBinding{
		Schema:         corerunnable.BindingSchemaV1,
		Identity:       pkg.GetIdentity(),
		PackageDigest:  pkg.GetDigest(),
		Facility:       &basev0.RunnableFacility{Kind: basev0.RunnableFacility_SERVICE},
		Implementation: &basev0.RunnableBinding_ServiceOperation{ServiceOperation: descriptor},
		Target:         target,
	}, pkg)
	if err != nil {
		return nil, err
	}
	if err = corerunnable.VerifyBinding(binding, pkg); err != nil {
		return nil, err
	}
	packageJSON, err := corerunnable.CanonicalJSON(pkg)
	if err != nil {
		return nil, err
	}
	bindingJSON, err := corerunnable.CanonicalJSON(binding)
	if err != nil {
		return nil, err
	}
	descriptors, err := methodDescriptors(module, operation.Entry.Service, operation.Entry.Endpoint, descriptor.GetOperation())
	if err != nil {
		return nil, err
	}
	return &PreparedRunnable{
		Package:     packageJSON,
		Binding:     bindingJSON,
		Operation:   operation.Operation,
		Descriptors: base64.StdEncoding.EncodeToString(descriptors),
	}, nil
}

// targetRevision identifies what a binding dispatches to: the package and the
// resolved address. A moved owner is a different binding, never the same one
// pointing elsewhere.
func targetRevision(packageDigest string, mapping *basev0.NetworkMapping) (string, error) {
	raw, err := corerunnable.CanonicalJSON(mapping)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(append([]byte(packageDigest+"\x00"), raw...))
	return "sha256:" + hex.EncodeToString(sum[:]), nil
}

// methodDescriptors reads the owner endpoint's published contract and keeps
// the file that declares the method's service, every file it imports, and the
// generic receipt service when the owner publishes it.
func methodDescriptors(module *resources.Module, service, endpoint, method string) ([]byte, error) {
	catalog, err := composition.LoadAPIContractCatalog(module.Dir())
	if err != nil {
		return nil, err
	}
	var path string
	for i := range catalog.Endpoints {
		published := &catalog.Endpoints[i]
		if published.Service == service && published.Endpoint == endpoint && published.Kind == composition.APIContractKindProtobuf {
			path = published.Path
		}
	}
	if path == "" {
		return nil, fmt.Errorf("%s/%s publishes no protobuf contract", service, endpoint)
	}
	raw, err := os.ReadFile(filepath.Join(module.Dir(), filepath.FromSlash(path)))
	if err != nil {
		return nil, err
	}
	var set descriptorpb.FileDescriptorSet
	if err := googleproto.Unmarshal(raw, &set); err != nil {
		return nil, err
	}
	return googleproto.MarshalOptions{Deterministic: true}.Marshal(descriptorClosure(&set, method))
}

// descriptorClosure keeps the file declaring the method's service and its
// transitive imports, in the set's own order.
func descriptorClosure(set *descriptorpb.FileDescriptorSet, method string) *descriptorpb.FileDescriptorSet {
	byName := map[string]*descriptorpb.FileDescriptorProto{}
	for _, file := range set.GetFile() {
		byName[file.GetName()] = file
	}
	serviceName := strings.TrimPrefix(method, "/")
	if cut := strings.LastIndex(serviceName, "/"); cut >= 0 {
		serviceName = serviceName[:cut]
	}
	keep := map[string]bool{}
	var visit func(string)
	visit = func(name string) {
		if keep[name] {
			return
		}
		file, ok := byName[name]
		if !ok {
			return
		}
		keep[name] = true
		for _, dependency := range file.GetDependency() {
			visit(dependency)
		}
	}
	for _, file := range set.GetFile() {
		for _, declared := range file.GetService() {
			full := declared.GetName()
			if file.GetPackage() != "" {
				full = file.GetPackage() + "." + full
			}
			if full == serviceName || full == "codefly.runnable.receipts.v0.Receipts" {
				visit(file.GetName())
			}
		}
	}
	out := &descriptorpb.FileDescriptorSet{}
	for _, file := range set.GetFile() {
		if keep[file.GetName()] {
			// A generic caller resolves types and methods; comments and
			// source locations are no part of that, and they are most of a
			// descriptor's size. Every prepared binding is delivered to its
			// installer as configuration, which the environment carries (a
			// process environment on a run), so what it does not need it must
			// not carry.
			lean := googleproto.CloneOf(file)
			lean.SourceCodeInfo = nil
			out.File = append(out.File, lean)
		}
	}
	return out
}

// endpointResolver resolves an owner endpoint the way a run or a render of the
// environment does: the native address locally, the in-cluster Service in a
// Kubernetes environment.
type endpointResolver struct {
	workspace *resources.Workspace
	env       *environments.Environment
	remote    *remotenetwork.RemoteManager
}

func newEndpointResolver(ctx context.Context, workspace *resources.Workspace, env *environments.Environment) (*endpointResolver, error) {
	resolver := &endpointResolver{workspace: workspace, env: env}
	if env.Local() {
		return resolver, nil
	}
	manager, err := configurations.NewManager(ctx, workspace)
	if err != nil {
		return nil, err
	}
	reader, err := configurations.NewConfigurationLocalReader(ctx, workspace)
	if err != nil {
		return nil, err
	}
	manager.WithLoader(reader)
	if resolver.remote, err = remotenetwork.NewRemoteManager(ctx, manager); err != nil {
		return nil, err
	}
	return resolver, nil
}

func (r *endpointResolver) resolve(ctx context.Context, module *resources.Module, serviceName, endpointName string) (*basev0.NetworkMapping, error) {
	service, err := module.LoadServiceFromName(ctx, serviceName)
	if err != nil {
		return nil, err
	}
	identity, err := service.Identity()
	if err != nil {
		return nil, err
	}
	endpoints, err := service.LoadEndpoints(ctx)
	if err != nil {
		return nil, err
	}
	var endpoint *basev0.Endpoint
	for _, candidate := range endpoints {
		if candidate.GetName() == endpointName {
			endpoint = candidate
		}
	}
	if endpoint == nil {
		return nil, fmt.Errorf("service %s/%s declares no endpoint %s", module.Name, serviceName, endpointName)
	}
	if r.env.Local() {
		instance := network.NativeFor(ctx, r.workspace.Name, identity.Module, identity.Name, r.env.NamingScope, endpoint)
		if instance == nil {
			return nil, fmt.Errorf("no native address for %s/%s/%s", module.Name, serviceName, endpointName)
		}
		return &basev0.NetworkMapping{Endpoint: endpoint, Instances: []*basev0.NetworkInstance{instance}}, nil
	}
	mappings, err := r.remote.GenerateNetworkMappings(ctx, r.env, r.workspace, identity, endpoints)
	if err != nil {
		return nil, err
	}
	for _, mapping := range mappings {
		if mapping.GetEndpoint().GetName() != endpointName {
			continue
		}
		container := resources.FilterNetworkInstance(ctx, mapping.GetInstances(), resources.NewContainerNetworkAccess())
		if container == nil {
			return nil, fmt.Errorf("%s/%s/%s resolves no in-cluster address in %s", module.Name, serviceName, endpointName, r.env.Name)
		}
		return &basev0.NetworkMapping{Endpoint: endpoint, Instances: []*basev0.NetworkInstance{container}}, nil
	}
	return nil, fmt.Errorf("%s/%s/%s resolves no mapping in %s", module.Name, serviceName, endpointName, r.env.Name)
}
