package update

import (
	"strings"
	"testing"
)

const vaultService = `# Code generated from deployment/topology.bindings.codefly.yaml. DO NOT EDIT.
name: vault
version: 0.0.0
agent:
    kind: codefly:service
    name: vault
    version: 0.0.22
    publisher: codefly.dev
service-dependencies:
    - name: cache
      endpoints:
        - name: read
        - name: write
secret-service-configurations:
    - name: vault
      entries:
        - key: vault_token
endpoints:
    - name: http
      visibility: module
spec:
    transit-key: api-keys
`

func TestRewriteAgentVersionPreservesUnmodeledKeysAndComments(t *testing.T) {
	// A plain service without a generated header — the surgical edit target.
	content := strings.TrimPrefix(vaultService, "# Code generated from deployment/topology.bindings.codefly.yaml. DO NOT EDIT.\n")

	out, err := rewriteAgentVersion([]byte(content), "0.0.24")
	if err != nil {
		t.Fatalf("rewriteAgentVersion: %v", err)
	}
	got := string(out)

	if !strings.Contains(got, "version: 0.0.24") {
		t.Errorf("agent version not bumped:\n%s", got)
	}
	if strings.Contains(got, "version: 0.0.22") {
		t.Errorf("old agent version still present:\n%s", got)
	}
	// The unmodeled block must survive the round-trip verbatim.
	if !strings.Contains(got, "secret-service-configurations:") ||
		!strings.Contains(got, "key: vault_token") {
		t.Errorf("unmodeled secret-service-configurations dropped:\n%s", got)
	}
	// No empty api keys injected on endpoint references (issue #3/#4).
	if strings.Contains(got, `api: ""`) {
		t.Errorf("empty api key injected:\n%s", got)
	}
	if !strings.Contains(got, "- name: read") || !strings.Contains(got, "- name: write") {
		t.Errorf("endpoint references altered:\n%s", got)
	}
	// The top-level service version (not the agent version) is untouched.
	if !strings.Contains(got, "version: 0.0.0") {
		t.Errorf("service version altered:\n%s", got)
	}
}

func TestRewriteAgentVersionPreservesNonCanonicalFormatting(t *testing.T) {
	// A hand-authored, 2-space-indented file must survive with only the version
	// token changed — no reflow to yaml.v3's canonical 4-space style.
	in := "name: vault\nagent:\n  name: vault\n  version: 0.0.22\nendpoints:\n  - name: http\n    visibility: module\n"
	want := "name: vault\nagent:\n  name: vault\n  version: 0.0.24\nendpoints:\n  - name: http\n    visibility: module\n"
	out, err := rewriteAgentVersion([]byte(in), "0.0.24")
	if err != nil {
		t.Fatalf("rewriteAgentVersion: %v", err)
	}
	if string(out) != want {
		t.Errorf("formatting not preserved:\ngot:\n%s\nwant:\n%s", out, want)
	}
}

func TestRewriteAgentVersionQuotedValue(t *testing.T) {
	in := "name: vault\nagent:\n    name: vault\n    version: \"0.0.22\"\n"
	want := "name: vault\nagent:\n    name: vault\n    version: \"0.0.24\"\n"
	out, err := rewriteAgentVersion([]byte(in), "0.0.24")
	if err != nil {
		t.Fatalf("rewriteAgentVersion: %v", err)
	}
	if string(out) != want {
		t.Errorf("quoted version not handled:\ngot:\n%s\nwant:\n%s", out, want)
	}
}

func TestRewriteAgentVersionNoChangeIsByteIdentical(t *testing.T) {
	out, err := rewriteAgentVersion([]byte(vaultService), "0.0.22")
	if err != nil {
		t.Fatalf("rewriteAgentVersion: %v", err)
	}
	if string(out) != vaultService {
		t.Errorf("no-op rewrite altered content:\n%s", out)
	}
}

func TestRewriteAgentVersionKeepsHeadComment(t *testing.T) {
	out, err := rewriteAgentVersion([]byte(vaultService), "0.0.24")
	if err != nil {
		t.Fatalf("rewriteAgentVersion: %v", err)
	}
	if !strings.Contains(string(out), "DO NOT EDIT.") {
		t.Errorf("head comment stripped:\n%s", out)
	}
}

func TestRewriteAgentVersionErrors(t *testing.T) {
	if _, err := rewriteAgentVersion([]byte("name: x\nversion: 1\n"), "0.0.1"); err == nil {
		t.Error("expected error when agent block is missing")
	}
	if _, err := rewriteAgentVersion([]byte("agent:\n    name: x\n"), "0.0.1"); err == nil {
		t.Error("expected error when agent has no version")
	}
}

func TestGeneratedMarker(t *testing.T) {
	source, generated := generatedMarker([]byte(vaultService))
	if !generated {
		t.Fatal("generated marker not detected")
	}
	if source != "deployment/topology.bindings.codefly.yaml" {
		t.Errorf("source = %q, want the topology bindings path", source)
	}

	if _, generated := generatedMarker([]byte("name: vault\nversion: 0.0.0\n")); generated {
		t.Error("plain service reported as generated")
	}

	// A marker without a "from" clause is still detected, with no source.
	source, generated = generatedMarker([]byte("# Code generated by hand. DO NOT EDIT.\nname: x\n"))
	if !generated || source != "" {
		t.Errorf("markerless source = %q generated = %v", source, generated)
	}

	// A "DO NOT EDIT" appearing only in the body, past the leading comments,
	// must not be mistaken for a generated-file marker.
	body := "name: x\nspec:\n    note: Code generated stuff. DO NOT EDIT.\n"
	if _, generated := generatedMarker([]byte(body)); generated {
		t.Error("body text mistaken for generated marker")
	}
}
