# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: management/views.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
import grpclib

from .v1.core import api


@dataclass
class ProjectView(betterproto.Message):
    name: str = betterproto.string_field(1)
    applications: List["ApplicationView"] = betterproto.message_field(3)


@dataclass
class ProjectInformationRequest(betterproto.Message):
    pass


@dataclass
class ProjectInformationResponse(betterproto.Message):
    project: "ProjectView" = betterproto.message_field(1)


@dataclass
class ApplicationView(betterproto.Message):
    application: str = betterproto.string_field(1)
    services: List["ServiceView"] = betterproto.message_field(2)


@dataclass
class ApplicationInformationRequest(betterproto.Message):
    application: str = betterproto.string_field(2)


@dataclass
class ApplicationInformationResponse(betterproto.Message):
    application: "ApplicationView" = betterproto.message_field(1)


@dataclass
class ServiceView(betterproto.Message):
    service: str = betterproto.string_field(1)
    endpoint: api.Endpoint = betterproto.message_field(5)


@dataclass
class ServiceInformationRequest(betterproto.Message):
    application: str = betterproto.string_field(1)
    service: str = betterproto.string_field(2)


@dataclass
class ServiceInformationResponse(betterproto.Message):
    pass


@dataclass
class PluginUsageRequest(betterproto.Message):
    publisher: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass
class Usage(betterproto.Message):
    application: str = betterproto.string_field(1)
    service: str = betterproto.string_field(2)


@dataclass
class PluginUsage(betterproto.Message):
    pass


@dataclass
class PluginUsageResponse(betterproto.Message):
    usage: "PluginUsage" = betterproto.message_field(1)


class WebStub(betterproto.ServiceStub):
    async def get_project_information(self) -> ProjectInformationResponse:
        request = ProjectInformationRequest()

        return await self._unary_unary(
            "/v1.applications.views.Web/GetProjectInformation",
            request,
            ProjectInformationResponse,
        )

    async def get_application_information(
        self, *, application: str = ""
    ) -> ApplicationInformationResponse:
        request = ApplicationInformationRequest()
        request.application = application

        return await self._unary_unary(
            "/v1.applications.views.Web/GetApplicationInformation",
            request,
            ApplicationInformationResponse,
        )

    async def get_service_information(
        self, *, application: str = "", service: str = ""
    ) -> ServiceInformationResponse:
        request = ServiceInformationRequest()
        request.application = application
        request.service = service

        return await self._unary_unary(
            "/v1.applications.views.Web/GetServiceInformation",
            request,
            ServiceInformationResponse,
        )
