name: Release

on:
  release:
    types: [released]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

#      - name: Cache Go Modules
#        uses: actions/cache@v3
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-

      - name: Build Binary Darwin Intel
        run: |
          GOOS=darwin GOARCH=amd64 go build -o codefly-darwin-amd64 main.go
      - name: Build Binary Darwin ARM
        run: |
          GOOS=darwin GOARCH=arm64 go build -o codefly-darwin-arm64 main.go
      - name: Build Binary Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o codefly-linux-x86_64 main.go
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: 'codefly-dev/cli-releases'
          token: ${{ secrets.GH_PAT }}
          path: 'cli-releases'

      - name: Copy File to Target Repository
        run: |
          cp ./codefly-darwin-amd64 ./cli-releases/
          cp ./codefly-darwin-arm64 ./cli-releases/
          cp ./codefly-linux-x86_64 ./cli-releases/

      - name: Configure Git with PAT
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git -C cli-releases remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/codefly-dev/cli-releases.git


      - name: Commit and Push to Target Repository
        run: |
          cd cli-releases
          git add codefly-darwin-amd64 codefly-darwin-arm64 codefly-linux-x86_64
          # Check for changes
          git diff --staged --quiet || {
            echo "No changes to commit"
            exit 0
          }
          git commit -m "Add new release binary"
          git push

      - name: Create Release in Target Repository
        id: create_release
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const repoName = 'cli-releases';
            const ownerName = 'codefly-dev';

            const releaseResponse = await github.repos.createRelease({
              owner: ownerName,
              repo: repoName,
              tag_name: '${{ github.ref }}',
              name: 'Release ${{ github.ref }}',
              draft: false,
              prerelease: false
            });

            core.setOutput('upload_url', releaseResponse.data.upload_url);

      - name: Upload AMD Binary to cli-releases Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cli-releases/codefly-darwin-amd64
          asset_name: codefly-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload ARM Binary to cli-releases Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cli-releases/codefly-darwin-arm64
          asset_name: codefly-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload Linux Binary to cli-releases Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cli-releases/codefly-linux-x86_64
          asset_name: codefly-linux-x86_64
          asset_content_type: application/octet-stream

      - name: Check out the formula repository
        uses: actions/checkout@v3
        with:
          repository: codefly-dev/homebrew-cli
          token: ${{ secrets.GH_PAT }}

      - name: Update the formula
        run: |
          # Update formula file with new version and SHA
          # This could be a script that updates the URL and sha256 fields in the formula file
          ./update_homebrew.sh ${{ github.event.release.tag_name }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git commit -am "Update formula to version ${{ github.event.release.tag_name }}"
          git push
